/* Price basis is scoped explicitly. Annual source ratios are not real flows. */
function updatePriceBasisNotice(){
  const basis=displayMode==='real'?`Pesos constantes de ${CONSTANT_PRICE_BASE}`:'Pesos corrientes';
  const note=document.getElementById('priceBasisNotice');
  if(note)note.textContent=`${basis}: se aplica a los ingresos provinciales con apertura mensual. Los porcentajes fiscales mantienen su definición. En deuda y en los demás bloques, fijate en la moneda y la fecha indicadas. El gasto nacional a precios constantes usa julio de 2026, explicitado en esa sección.`;
  for(const id of ['kTopYtd','kRonYtd']){const card=document.getElementById(id)?.closest('.kcard');if(!card)continue;const tag=card.querySelector('.pulse-tag');if(tag)tag.textContent='Flujo acumulado · '+basis;}
}
function initInflationHistory(){
  const note=document.createElement('p');note.id='priceBasisNotice';note.className='federal-note';note.setAttribute('aria-live','polite');document.querySelector('.reading-options').append(note);updatePriceBasisNotice();
  const selector=document.getElementById('valueModeSelector');selector.setAttribute('aria-label','Unidad de los ingresos provinciales mensuales');
  const details=document.createElement('details');details.className='history-values';details.id='fiscalArchivePanel';details.innerHTML='<summary>Archivo fiscal completo · ranking desde 2015 y cuentas anuales desde 2017</summary><div id="fiscalArchiveContent"><p>Cargando las series históricas…</p></div>';
  document.querySelector('#fiscalHistoryPanel .federal-content').append(details);
  let loaded=false;details.addEventListener('toggle',async()=>{if(!details.open||loaded)return;loaded=true;const host=details.querySelector('#fiscalArchiveContent');try{
    const d=await operationFile('fiscal_archive.json');host.replaceChildren();
    const intro=document.createElement('p');intro.textContent=`Se revisaron ${d.reports.length} informes completos. Los montos fiscales de doce meses empiezan en 4T21. Los anexos permiten ir más atrás con porcentajes anuales y posiciones en el ranking. Cuando el informe no trae un monto, no lo reconstruimos a partir de un porcentaje.`;host.append(intro);
    const method=document.createElement('p');method.className='federal-note';method.textContent=d.method;host.append(method);
    const label=document.createElement('label');label.textContent='Serie del archivo ';const select=document.createElement('select');select.id='fiscalArchiveMetric';for(const [value,text]of [['financial','Resultado financiero / ingresos'],['primary','Resultado primario / ingresos'],['tax','Impuestos provinciales / ingresos'],['royalties','Regalías / ingresos'],['national_tax','Impuestos nacionales / ingresos'],['social_income','Ingresos de seguridad social / ingresos'],['other_income','Otros ingresos / ingresos'],['personnel','Personal / ingresos'],['current_transfers','Transferencias corrientes / ingresos'],['capital','Gasto de capital / ingresos'],['social_spend','Gasto de seguridad social / ingresos'],['other_spend','Otros gastos / ingresos'],['primary_spend','Gasto primario / ingresos'],['interest_signed','Intereses pagados (signo negativo) / ingresos'],['rank','Posición en el ranking trimestral']]){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}label.append(select);host.append(label);
    const box=document.createElement('div');box.className='history-chart';box.style.height='320px';const canvas=document.createElement('canvas');canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Historia anual y ranking según los anexos fiscales');box.append(canvas);host.append(box);
    const reading=document.createElement('p');host.append(reading);const values=document.createElement('details');values.className='history-values';values.innerHTML='<summary>Ver valores y períodos</summary>';const table=document.createElement('div');values.append(table);host.append(values);let chart;
    const draw=()=>{const province=document.getElementById('psel').value,rank=select.value==='rank';const rows=(rank?d.rank_history:d.annual_ratios).filter(r=>r.province===province).sort((a,b)=>(a.period||a.year).localeCompare(b.period||b.year));chart?.destroy();
      if(typeof Chart!=='undefined')chart=new Chart(canvas,{type:'line',plugins:[{id:'archiveTheme',beforeUpdate(c){const color=getComputedStyle(document.documentElement).getPropertyValue('--blue').trim();c.data.datasets[0].borderColor=color;c.data.datasets[0].pointBackgroundColor=color;}}],data:{labels:rows.map(r=>r.period||r.year),datasets:[{label:select.selectedOptions[0].textContent,data:rows.map(r=>rank?r.rank:r[select.value]),borderColor:'#2863aa',pointRadius:2,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{maxTicksLimit:8}},y:{reverse:rank,title:{display:true,text:rank?'Posición publicada (1 = primera)':'% de ingresos nominales'}}}}});
      reading.textContent=`${province} · ${rank?'Ranking trimestral publicado; los universos pueden cambiar entre informes.':'Años completos, en % de ingresos totales nominales. No son variaciones reales ni doce meses móviles.'} ${rows.length} observaciones. Se usa la publicación más reciente disponible para cada período.`;
      table.replaceChildren(managementTable('Valores de la serie',['Período','Valor'],rows.map(r=>[r.period||r.year,fnum(rank?r.rank:r[select.value])+(rank?'':'%')])));};
    select.onchange=draw;document.getElementById('psel').addEventListener('change',draw);draw();
    managementSource(host,'data/fiscal_annual_history.csv','Descargar cuentas anuales en CSV');managementSource(host,'data/fiscal_rank_history.csv','Descargar ranking histórico en CSV');managementSource(host,'data/fiscal_archive.json','Descargar historia y catálogo de los informes');managementSource(host,'data/fiscal_archive_vintages.json','Descargar todas las versiones extraídas');managementSource(host,'data/inflation_audit.json','Ver auditoría del IPC y fórmula de ajuste');
    const exceptions=document.createElement('p');exceptions.className='federal-note';exceptions.textContent=`Se registraron ${d.exceptions.length} posiciones publicadas como cero en las distintas versiones del ranking. Se muestran como «sin dato», porque cero no es una posición válida. El detalle está en la descarga. Los gráficos sin valor numérico explícito no se convierten en observaciones.`;host.append(exceptions);
  }catch(error){loaded=false;host.textContent='No se pudo cargar el archivo histórico. Recargá la página para reintentar.';console.error(error);}});
}
