/* Public evidence and user-entered scenarios are separate. No input is persisted. */
let spendChart=null;
const operationRequests=new Map();
const operationFile=name=>{if(!operationRequests.has(name))operationRequests.set(name,fetch('data/'+name+'?v=20260906-4').then(r=>{if(!r.ok)throw Error('Fuente no disponible');return r.json();}).catch(error=>{operationRequests.delete(name);throw error;}));return operationRequests.get(name);};
const operationsData=()=>Promise.all([operationFile('national_operations.json'),operationFile('treasury_obligations.json')]);
function managementTable(caption,headers,rows){
  const box=document.createElement('div');box.className='federal-table';const table=document.createElement('table');table.className='management-table';box.append(table);table.createCaption().textContent=caption;
  const head=table.createTHead().insertRow();headers.forEach(h=>{const th=document.createElement('th');th.scope='col';th.textContent=h;head.append(th);});
  const body=table.createTBody();rows.forEach(values=>{const tr=body.insertRow();values.forEach((v,i)=>{const cell=document.createElement(i?'td':'th');if(!i)cell.scope='row';cell.textContent=v;tr.append(cell);});});return box;
}
function managementSource(parent,url,label){const p=document.createElement('p'),a=document.createElement('a');p.className='federal-note';a.href=url;a.target='_blank';a.rel='noopener';a.textContent=label;p.append(a);parent.append(p);}
function initManagementDesign(){
  document.querySelector('#heroTitle').textContent='Tablero para la gestión';
  const bar=document.querySelector('.dashboard-command-bar'),options=document.createElement('details');options.className='reading-options';options.innerHTML='<summary>Lectura y unidades</summary><div class="reading-options-grid"></div>';
  for(const id of ['profileSelector','periodSelector','valueModeSelector'])options.lastElementChild.append(document.getElementById(id).closest('.command-field'));
  bar.append(options);
  const rank=document.querySelector('.pulse-rank .k-lbl');if(rank)rank.textContent='Ranking fiscal 1816';
  const nav=document.querySelector('.federal-shortcuts'),button=document.createElement('button');button.id='openOperations';button.type='button';button.textContent='Caja y vencimientos';button.setAttribute('aria-controls','operationsPanel');button.setAttribute('aria-expanded','false');nav.append(button);
  const panel=document.createElement('details');panel.id='operationsPanel';panel.innerHTML='<summary>Caja, obligaciones y escenarios de pago</summary><div class="federal-content" id="operationsContent"><p>Cargando fuentes de Tesorería…</p></div>';document.querySelector('#federalTools').append(panel);
  panel.addEventListener('toggle',()=>button.setAttribute('aria-expanded',String(panel.open)));
  button.onclick=()=>{const open=!panel.open;for(const p of document.querySelectorAll('#federalTools > details'))p.open=false;panel.open=open;if(open)panel.scrollIntoView({behavior:'smooth'});};
  renderOperationsPanel();
  renderFederalBenchmarks();
  const mobile=document.createElement('label');mobile.className='mobile-view-picker';mobile.textContent='Vista del tablero';const picker=document.createElement('select');picker.id='mobileViewPicker';mobile.append(picker);
  for(const [value,text] of [['summary','Resumen provincial'],['debt','Solvencia y deuda'],['income','Ingresos y gasto'],['federal','Relación con Nación'],['comparison','Comparación provincial'],['results','Resultados de gobierno'],['openHistory','Historia fiscal'],['openMap','Mapa de Argentina'],['openNation','Economía nacional'],['openOperations','Caja y vencimientos'],['openGuide','Cómo leer los datos']]){const o=document.createElement('option');o.value=value;o.textContent=text;picker.append(o);}
  document.querySelector('.dashboard-nav').after(mobile);picker.onchange=()=>{if(picker.value.startsWith('open'))document.getElementById(picker.value).click();else{for(const p of document.querySelectorAll('#federalTools > details'))p.open=false;applyDashboardView(picker.value);}};
  const toolKeys={fiscalHistoryPanel:'openHistory',fiscalMapPanel:'openMap',nationalPanel:'openNation',operationsPanel:'openOperations',fiscalGuide:'openGuide'};
  for(const p of document.querySelectorAll('#federalTools > details'))p.addEventListener('toggle',()=>{document.body.classList.toggle('national-context',document.querySelector('#nationalPanel').open||panel.open);if(p.open)picker.value=toolKeys[p.id];else if(!document.querySelector('#federalTools > details[open]'))picker.value=dashboardView;});
  document.querySelector('.dashboard-nav').addEventListener('click',e=>{const button=e.target.closest('[data-view]');if(button)picker.value=button.dataset.view;});
  const targets=document.createElement('div');targets.className='targets-download';targets.innerHTML='<h3>De los resultados a las metas</h3><p>Una meta necesita indicador, punto de partida, plazo y responsable. La matriz contiene las bases observadas de las 24 jurisdicciones; las metas quedan vacías para que la gestión las defina. No confunde un objetivo con un resultado ya alcanzado.</p><a class="management-action" href="data/management_targets_template.csv" download>Descargar matriz de metas para completar</a>';document.querySelector('#resultsView').append(targets);renderManagementProposals(targets);
}
async function renderFederalBenchmarks(){
  const host=document.createElement('details');host.className='history-values';host.innerHTML='<summary>Comparar promedio, mediana y valor por habitante</summary>';document.querySelector('#fairPanelPerCapitaNote').after(host);
  try{const r=await fetch('data/federal_benchmarks.json?v=20260906-4');if(!r.ok)throw Error('source');const d=await r.json();host.append(managementTable('RON 2025 · 23 provincias sin CABA',['Referencia','Pesos por habitante'],[['Promedio simple',fnum(d.simple_mean)],['Mediana',fnum(d.median)],['Importe conjunto por habitante',fnum(d.population_weighted_mean)]]));const p=document.createElement('p');p.className='federal-note';p.textContent='El promedio simple da el mismo peso a cada provincia; la mediana es el valor central. El importe conjunto por habitante pondera por población. Los tres usan las mismas 23 provincias y población del Censo 2022, no una proyección demográfica de 2025.';host.append(p);managementSource(host,'data/federal_benchmarks.json','Ver datos, universo y cálculo');}catch{const p=document.createElement('p');p.textContent='No se pudieron cargar las referencias comparables.';host.append(p);}
}
async function renderNationalOperations(host){
  try{const d=await operationFile('national_operations.json'),s=d.spending,section=document.createElement('section');section.id='national-spending';section.className='national-section';
    section.innerHTML='<h3>Gasto nacional: qué pesa y qué cambió</h3><p>Julio de 2026 · Sector Público Nacional, base caja. La variación real compara julio con julio, descontando el IPC nacional del mismo período.</p>';
    const total=s.rows.find(r=>r.id==='primary_spend'),components=s.rows.filter(r=>r.composition);
    section.append(managementTable('Composición del gasto primario · millones de pesos corrientes',['Componente','Julio 2026','% del gasto','Cambio real interanual'],components.map(r=>[r.label,fnum(r.value),fnum(r.value/total.value*100)+'%',fnum(r.real_yoy_pct)+'%'])));
    const note=document.createElement('p');note.className='federal-note';note.textContent=s.transfer_scope;section.append(note);
    const detail=document.createElement('details');detail.className='history-values';detail.innerHTML='<summary>Ver ingresos, intereses y aperturas sociales</summary>';detail.append(managementTable('Aperturas y totales · las subcategorías no se suman otra vez',['Concepto','Julio 2026','Julio 2025','Cambio real'],s.rows.filter(r=>!r.composition).map(r=>[r.label,fnum(r.value),fnum(r.previous),fnum(r.real_yoy_pct)+'%'])));section.append(detail);
    const label=document.createElement('label');label.textContent='Evolución mensual ';const select=document.createElement('select');select.id='nationalSpendMetric';select.className='psel';for(const r of [total,...components]){const o=document.createElement('option');o.value=r.id;o.textContent=r.label;select.append(o);}label.append(select);section.append(label);
    const chartBox=document.createElement('div');chartBox.className='history-chart';chartBox.innerHTML='<canvas id="nationalSpendChart" role="img" aria-label="Gasto mensual a precios de julio de 2026"></canvas>';section.append(chartBox);const chartNote=document.createElement('p');chartNote.className='federal-note';chartNote.textContent='Millones de pesos de julio de 2026. Cada mes se deflacta con su IPC. Serie sin ajuste estacional: aguinaldos y calendarios de pagos pueden explicar movimientos mensuales.';section.append(chartNote);
    const chartTable=document.createElement('details');chartTable.className='history-values';chartTable.innerHTML='<summary>Ver valores mensuales</summary>';section.append(chartTable);
    const draw=()=>{const rows=s.monthly_2026.filter(r=>r.id===select.value);spendChart?.destroy();if(typeof Chart!=='undefined')spendChart=new Chart(chartBox.firstElementChild,{type:'bar',data:{labels:rows.map(r=>r.period),datasets:[{label:'Gasto a precios de julio 2026',data:rows.map(r=>r.real_july2026),backgroundColor:'#79add0'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#c2cede'}},y:{ticks:{color:'#c2cede'}}}}});chartTable.querySelector('.federal-table')?.remove();chartTable.append(managementTable('Millones de pesos',['Mes','Corrientes','A precios de julio 2026'],rows.map(r=>[r.period,fnum(r.value),fnum(r.real_july2026)])));};select.onchange=draw;
    managementSource(section,s.source_url,'Hacienda · IMIG julio 2026 · publicado el 18/08/2026');host.append(section);draw();
  }catch{const p=document.createElement('p');p.textContent='El detalle de gasto no pudo cargarse. Los otros indicadores conservan sus propias fuentes.';host.append(p);}
}
function calculateCashScenario(values){
  const keys=['cash','revenue','spending','principal','interest','financing'];
  if(keys.some(k=>typeof values[k]!=='number'||!Number.isFinite(values[k])||values[k]<0))return null;
  const available=values.cash+values.revenue+values.financing,payments=values.spending+values.principal+values.interest;
  return {available,payments,closing:available-payments,gap:Math.max(0,payments-available)};
}
if(typeof module!=='undefined'&&module.exports)module.exports={calculateCashScenario};
async function renderOperationsPanel(){
  const host=document.querySelector('#operationsContent');
  try{const [d,t]=await operationsData();host.innerHTML='<h3>Obligaciones nacionales publicadas</h3><p>Ámbito: Nación. Estos datos son independientes del resumen provincial. El calculador de abajo permite elegir la jurisdicción del escenario.</p>';
    const grid=document.createElement('div');grid.className='ops-grid';
    for(const [label,value,period] of [['Deuda exigible registrada',t.payables.total,'Julio 2026 · Administración Central'],['Adelantos BCRA que vencen en septiembre',t.bcra_advances.september_2026,'Calendario al 31/08/2026'],['Adelantos BCRA que vencen en 4T26',t.bcra_advances.q4_2026,'Calendario al 31/08/2026']]){const card=document.createElement('article');card.className='ops-card';const title=document.createElement('p');title.className='ops-label';title.textContent=label;const valueEl=document.createElement('strong');valueEl.textContent=fnum(value);const foot=document.createElement('p');foot.className='ops-sub';foot.textContent='Millones de pesos · '+period;card.append(title,valueEl,foot);grid.append(card);}host.append(grid);
    for(const item of [t.payables,t.bcra_advances]){const p=document.createElement('p');p.className='federal-note';p.textContent=item.limitation;host.append(p);managementSource(host,item.source_url,'Fuente: Tesorería General de la Nación');}
    const detail=document.createElement('details');detail.className='history-values';detail.innerHTML='<summary>Ver deuda exigible por componente e historia mensual</summary>';detail.append(managementTable('Julio 2026 · millones de pesos',['Concepto','Saldo'],t.payables.components.map(r=>[r.label,fnum(r.value)])));detail.append(managementTable('Saldos mensuales, no sumables',['Mes','Deuda exigible'],t.payables.monthly.map(r=>[r.period,fnum(r.value)])));managementSource(detail,t.payables.history_source_url,'Serie mensual TGN');host.append(detail);
    const maturity=document.createElement('details');maturity.className='history-values';maturity.innerHTML='<summary>Perfil completo de vencimientos · referencia al 31/03/2026</summary>';const p=document.createElement('p');p.textContent=d.maturities.reading;maturity.append(p);maturity.append(managementTable('Proyección publicada para abril 2026–marzo 2027 · USD millones equivalentes',['Mes proyectado','Capital','Intereses','Total'],d.maturities.rows.map(r=>[r.period,fnum(r.capital),fnum(r.interest),fnum(r.total)])));managementSource(maturity,d.maturities.source_url,'Finanzas · cuadro A.3.1');host.append(maturity);
    const section=document.createElement('section');section.className='national-section';section.innerHTML='<h3>Escenario de caja a 30, 90 o 365 días</h3><p>Completá los supuestos de la jurisdicción y del horizonte elegido. El cálculo se hace en esta pantalla; no se guarda ni se envía. No carga automáticamente el perfil histórico de deuda.</p><p class="federal-note">Usá todos los importes en millones de pesos nominales. Los pagos primarios incluyen salarios, aguinaldo, inversión y pagos de obligaciones previas que correspondan al horizonte; excluye capital e intereses de deuda, que se cargan separados. No repitas un pago en dos casilleros. Caja inicial: solamente fondos conciliados y utilizables.</p><div class="scenario-grid"><label>Jurisdicción<select id="scenarioJurisdiction"></select></label><label>Horizonte<select id="scenarioHorizon"><option value="30">30 días</option><option value="90">90 días</option><option value="365">365 días</option></select></label><label>Fecha de partida<input id="scenarioDate" type="date"></label></div><div class="scenario-grid" id="scenarioInputs"></div><p id="scenarioOutput" class="scenario-output" aria-live="polite">Faltan los supuestos. No se calcula un saldo con casilleros vacíos.</p><button type="button" class="management-action" id="clearScenario">Limpiar supuestos</button><details class="history-values"><summary>Qué hace falta para acreditar caja libre</summary><ul id="cashRequirements"></ul></details>';host.append(section);renderUpdatedMaturities(host);
    const jurisdiction=section.querySelector('#scenarioJurisdiction');for(const value of ['Nación',...[...document.querySelector('#psel').options].map(o=>o.value)]){const option=document.createElement('option');option.value=value;option.textContent=value;jurisdiction.append(option);}
    for(const item of t.free_cash.required_inputs){const li=document.createElement('li');li.textContent=item;section.querySelector('#cashRequirements').append(li);}
    const fields=[['cash','Caja inicial libre'],['revenue','Ingresos previstos'],['spending','Pagos primarios (incluye inversión)'],['principal','Capital de deuda a pagar'],['interest','Intereses a pagar'],['financing','Financiamiento confirmado']];
    const inputs=section.querySelector('#scenarioInputs');fields.forEach(([key,title])=>{const label=document.createElement('label');label.textContent=title;const input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.id='cash_'+key;input.placeholder='Sin cargar';label.append(input);inputs.append(label);});
    const output=section.querySelector('#scenarioOutput');const update=()=>{const values=Object.fromEntries(fields.map(([key])=>{const v=document.getElementById('cash_'+key).value;return [key,v.trim()===''?null:Number(v)];}));const result=calculateCashScenario(values),date=section.querySelector('#scenarioDate').value;if(!result||!date){output.textContent='Completá fecha y todos los supuestos con valores no negativos. Cargá 0 explícitamente cuando corresponda.';return;}output.replaceChildren();const strong=document.createElement('strong');strong.textContent=`Saldo calculado: $ ${fnum(result.closing)} millones`;const p=document.createElement('p');p.textContent=`${jurisdiction.value} · ${section.querySelector('#scenarioHorizon').value} días desde ${date}. ${result.gap>0?'Faltante a financiar: $ '+fnum(result.gap)+' millones.':'Los supuestos cubren los pagos cargados.'} Es un escenario ingresado por el usuario, no un dato oficial ni una garantía de liquidez.`;output.append(strong,p);};
    inputs.addEventListener('input',update);section.querySelector('#scenarioDate').addEventListener('change',update);
    const clear=()=>{inputs.querySelectorAll('input').forEach(i=>i.value='');output.textContent='Supuestos vacíos para esta jurisdicción y horizonte. Cargá los datos correspondientes.';};jurisdiction.onchange=clear;section.querySelector('#scenarioHorizon').onchange=clear;section.querySelector('#clearScenario').onclick=()=>{clear();section.querySelector('#scenarioDate').value='';};initCashReconciliation(section);
  }catch{host.textContent='No se pudieron cargar las fuentes de obligaciones. No se interpreta el faltante como ausencia de deuda.';}
}
