"""Package the audited municipal research for the static dashboard (stdlib only)."""
import argparse
import csv
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def read_csv(path):
    with path.open(encoding='utf-8-sig', newline='') as f:
        return list(csv.DictReader(f))


def value(text):
    if text in ('', None):
        return None
    if text in ('True', 'False'):
        return text == 'True'
    try:
        n = float(text)
        return round(n, 6) if math.isfinite(n) else None
    except ValueError:
        return text


def build(folder):
    base = read_csv(folder / 'rankings_base_135_municipios.csv')
    municipalities = {}
    for row in base:
        ident = row.pop('municipality_id')
        municipalities[ident] = {'id': ident, **{k: value(v) for k, v in row.items()}, 'transfers': [], 'employment': [], 'sectors': [], 'fiscal': None}
    assert len(municipalities) == 135
    ipc = {r['period']: float(r['ipc_index']) for r in read_csv(folder / 'ipc_indec_verificado.csv')}
    for r in read_csv(folder / 'datos_de_entrada/transferencias_mensuales_2025_2026_muestra.csv'):
        factor = ipc['2026-07'] / ipc[r['period']]
        municipalities[r['municipality_id']]['transfers'].append([r['period'], round(float(r['total_transfers_ars']) * factor, 2), round(float(r['coparticipation_gross_ars']) * factor, 2)])
    employment = {i: {} for i in municipalities}
    for r in read_csv(folder / 'datos_de_entrada/empleo_salarios_oede_muestra.csv'):
        period = r['period']
        employment[r['municipality_id']].setdefault(period, {})[r['metric']] = float(r['value'])
    for ident, series in employment.items():
        municipalities[ident]['employment'] = [[p, r.get('employment'), round(r['wage_ars'] * ipc['2026-07'] / ipc[p], 2) if r.get('wage_ars') is not None else None] for p, r in sorted(series.items())]
    for r in read_csv(folder / 'empleo_sectorial_pba_2019_2025.csv'):
        if r['Periodo'] == '202512':
            municipalities[r['municipality_id']]['sectors'].append({'name': r['Sector'], 'jobs': value(r['empleo_num'])})
    for r in read_csv(folder / 'muestra_fiscal_junio2026.csv'):
        municipalities[r['municipality_id']]['fiscal'] = {k: value(v) for k, v in r.items() if k not in ('municipality_id', 'municipio')}
    for m in municipalities.values():
        m['transfers'].sort()
        assert len(m['transfers']) == 19 and len(m['employment']) == 84
        assert m['poblacion_2022'] > 0
    summary = json.loads((folder / 'resultados_verificados.json').read_text(encoding='utf-8'))
    controls = json.loads((folder / 'control_y_recaudacion.json').read_text(encoding='utf-8'))
    data = {'version': 1, 'generated': '2026-09-07', 'priceBase': '2026-07', 'populationYear': 2022, 'summary': summary, 'provincialRevenue': controls['recaudacion_real_ene_jul_2026_vs2025_pct'], 'municipalities': list(municipalities.values())}
    target = ROOT / 'municipios/data/dashboard.json'
    target.write_text(json.dumps(data, ensure_ascii=False, separators=(',', ':'), allow_nan=False), encoding='utf-8')
    manifest = [{'file': str(p.relative_to(folder)).replace('\\', '/'), 'sha256': hashlib.sha256(p.read_bytes()).hexdigest()} for p in folder.rglob('*.csv')]
    (target.parent / 'build-manifest.json').write_text(json.dumps({'generated': '2026-09-07', 'inputs': manifest, 'coverage': 135}, indent=2), encoding='utf-8')
    (target.parent / 'fuentes.csv').write_bytes((folder / 'fuentes_y_huellas.csv').read_bytes())
    # Serve a conventional deferred script on static hosts, independent of .mjs MIME configuration.
    model = (ROOT / 'municipios/model.mjs').read_text(encoding='utf-8').replace('export ', '')
    app = (ROOT / 'municipios/app.mjs').read_text(encoding='utf-8').split('\n', 1)[1]
    (ROOT / 'municipios/app.js').write_text("/* Generated by scripts_build_municipal_dashboard.py. */\n(function(){'use strict';\n" + model + '\n' + app + '\n})();\n', encoding='utf-8')
    print(f'{target.name}: {len(municipalities)} municipalities; {target.stat().st_size:,} bytes')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input-dir', type=Path, required=True)
    build(parser.parse_args().input_dir)
