const test=require('node:test');const assert=require('node:assert/strict');
const {normalizeReadingProfile,buildProfileReadings}=require('../profile-readings.js');
const roles=['governor','hacienda','press'];
test('only three profiles, including migration of saved legacy choices',()=>{assert.equal(normalizeReadingProfile('deep'),'hacienda');assert.equal(normalizeReadingProfile('analyst'),'press');assert.equal(normalizeReadingProfile('unknown'),'governor');});
test('every section changes interpretation across all three profiles while keeping facts',()=>{const all=roles.map(r=>buildProfileReadings(r,{province:'Córdoba',rf:-2,rp:1,debt:20,period:'enero–marzo 2026'}));assert.equal(Object.keys(all[0]).length,11);for(const section of Object.keys(all[0]))assert.equal(new Set(all.map(r=>r[section][1])).size,3,section);for(const r of all){assert.match(r.summary[0],/Córdoba.*-2%.*enero–marzo 2026/);assert.match(r.debt[0],/\$100.*\$20/);}});
test('missing fiscal observations do not become a diagnosis or numeric zero',()=>{for(const role of roles){const r=buildProfileReadings(role,{province:'La Pampa'});assert.match(r.summary[0],/falta un resultado/);assert.doesNotMatch(r.summary[0],/0%/);assert.match(r.debt[0],/Falta/);}});
test('zero, deficit and surplus have distinct conclusions',()=>{for(const role of roles){const conclusions=[-1,0,1].map(rf=>buildProfileReadings(role,{province:'Prueba',rf,rp:0}).summary[1]);assert.equal(new Set(conclusions).size,3);}});
test('minister differentiates a primary deficit from interest pressure',()=>{const primary=buildProfileReadings('hacienda',{province:'Prueba',rf:-5,rp:-2});const interest=buildProfileReadings('hacienda',{province:'Prueba',rf:-5,rp:2});assert.match(primary.summary[1],/empieza antes de intereses/);assert.match(interest.summary[1],/costo de intereses/);});
const {buildSheetExplanation}=require('../profile-readings.js');
test('rich analysis explains only observed fiscal differences',()=>{const text=buildSheetExplanation('summary',{rf:-6.58,rp:-2.74});assert.match(text,/antes de pagar intereses/);assert.match(text,/3,84 puntos/);const missing=buildSheetExplanation('summary',{rf:null,rp:null});assert.match(missing,/información que falta/);assert.doesNotMatch(missing,/0 puntos/);});
test('debt narrative does not turn history into a future schedule',()=>{const text=buildSheetExplanation('debt',{services:{total_ars_m:100,amortization_ars_m:70,interest_ars_m:30}});assert.match(text,/compromisos registrados en años anteriores/);assert.match(text,/falta el calendario de próximos pagos/);assert.doesNotMatch(text,/mayor importe.*2026/);const projected=buildSheetExplanation('debt',{projection:{rows:[{year:2026,total_ars_m:10},{year:2027,total_ars_m:20}]}});assert.match(projected,/mayor importe anual en 2027: \$20 millones/);assert.match(projected,/descontar los pagos ya realizados/);});
test('debt priority follows schedule coverage and does not mislabel loading as missing',()=>{
 const pending=buildProfileReadings('governor',{debt:45.23});
 assert.match(pending.debt[0],/\$100.*\$45,23/);
 assert.match(pending.debt[1],/Armar un calendario/);
 assert.doesNotMatch(pending.debt[1],/años de mayor vencimiento/);
 const available=buildProfileReadings('governor',{debt:45.23,debtScheduleStatus:'verified'});
 assert.match(available.debt[1],/Revisar los próximos pagos/);
 const loading=buildSheetExplanation('debt',{debtScheduleStatus:'loading'});
 assert.doesNotMatch(loading,/falta el calendario/);
 assert.match(buildProfileReadings('governor',{debt:0}).debt[0],/\$100.*\$0/);
});
