/* Observed 2026 management data. Never uses projected inflation for actual flows. */
(() => {
  'use strict';
  const M=window.NationalManagementMath,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,d=1)=>M.finite(v)?new Intl.NumberFormat('es-AR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v):'Sin dato';
  const pct=v=>M.finite(v)?`${v>0?'+':''}${num(v)}%`:'Sin comparación';
  const sign=v=>!M.finite(v)?'':v<0?'negative':v>0?'positive':'';
  const money=v=>{if(!M.finite(v))return 'Sin dato';const a=Math.abs(v),scale=a>=1e6?1e6:a>=1000?1000:1;return `${v<0?'−':''}$${num(a/scale,a>0&&a<1?2:1)} ${scale===1e6?'billones':scale===1000?'mil millones':'millones'}`;};
  const usd=v=>M.finite(v)?`USD ${num(v,0)} M`:'Sin dato';
  const fold=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const period=v=>{const [y,m]=v.split('-');return `${['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'][+m-1]} ${y}`;};
  const pages=[['ejecucion','Presupuesto'],['caja','Caja'],['deuda-nacional','Deuda'],['provincias-nacion','Provincias'],['metas','Prestaciones'],['obras-ejecucion','Obras'],['historia-ejecucion','Historia']];
  let D,price='nominal',current='ejecucion',quarter=2,metaLimit=12,workLimit=12,provinceId=6,provinceRank='variacion_real_pct';
  const rawCache=new Map();
  const unit=()=>price==='real'?'Pesos de agosto de 2026':'Pesos corrientes';
  const wrapper=document.querySelector('[data-page="ejecucion"]');
  wrapper.insertAdjacentHTML('afterbegin',`<nav class="management-nav" aria-label="Explorar la gestión 2026">${pages.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><p id="management-status" role="status">Cargando los datos de gestión…</p>`);
  $('ejecucion').dataset.managementPanel='ejecucion';
  for(const [id,label] of pages.slice(1))wrapper.insertAdjacentHTML('beforeend',`<section id="${id}" class="chapter management-panel" data-management-panel="${id}" hidden><p class="eyebrow">Gestión 2026 / ${label}</p><div id="${id}-content"></div></section>`);
  $('ejecucion').insertAdjacentHTML('afterbegin','<div id="management-execution"></div>');
  $('metodo').insertAdjacentHTML('beforeend','<section id="management-downloads" class="management-downloads"></section>');
  $('inicio').insertAdjacentHTML('beforeend','<div id="management-preview" class="management-preview"></div>');
  const stat=(label,value,note,cls='')=>`<article><h3>${esc(label)}</h3><strong class="management-number ${cls}">${value}</strong><p>${esc(note)}</p></article>`;
  const table=(head,rows,caption)=>`<div class="table-wrap"><table><caption>${esc(caption)}</caption><thead><tr>${head.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map((v,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${v}</${i?'td':'th'}>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}">No hay resultados para esta búsqueda.</td></tr>`}</tbody></table></div>`;
  const cell=(v,format=num)=>`<span class="${M.finite(v)&&v<0?'negative':''}">${format(v)}</span>`;
  const source=(key)=>{const d=D.datasets[key];return `<p class="note management-source">${esc(d.scope)} · <a href="${esc(d.sources[0].url)}" target="_blank" rel="noopener">Documento oficial ↗</a> · <a href="${esc(d.files.csv.path)}" download>Descargar datos CSV ↓</a></p>`;};
  const bars=(rows,formatter=money)=>{const max=Math.max(1,...rows.filter(r=>M.finite(r.value)).map(r=>Math.abs(r.value)));return `<div class="management-bars">${rows.map(r=>`<div class="management-bar-row"><div><span>${esc(r.name)}</span><strong class="${r.value<0?'negative':''}">${formatter(r.value)}</strong></div><div class="management-track"><span style="width:${M.finite(r.value)?Math.abs(r.value)/max*100:0}%;${r.value<0?'background:var(--negative)':''}"></span></div>${r.note?`<small>${esc(r.note)}</small>`:''}</div>`).join('')}</div>`;};
  const ready=()=>{if(!D)return;route();renderExecution();preview();};
  function route(){
    const anchor=location.hash.slice(1);
    current=pages.some(([id])=>id===anchor)?anchor:'ejecucion';
    document.querySelectorAll('[data-management-panel]').forEach(e=>e.hidden=e.dataset.managementPanel!==current);
    document.querySelectorAll('.management-nav a').forEach(e=>e.setAttribute('aria-current',e.hash==='#'+current?'page':'false'));
    if(!D)return;
    ({ejecucion:renderExecution,caja:renderCash,'deuda-nacional':renderDebt,'provincias-nacion':renderProvinces,metas:renderMetas,'obras-ejecucion':renderWorks,'historia-ejecucion':renderHistory})[current]();
  }
  function preview(){
    const cash=D.cash.comparison.find(r=>r.indicador==='resultado_financiero'),real=D.execution.comparison.find(r=>r.etapa==='credito_devengado');
    $('management-preview').innerHTML=`<div><p class="eyebrow">Además del proyecto / Gestión 2026</p><h2 tabindex="-1">Qué pasa con las cuentas hoy</h2><p>El gasto ejecutado bajó <strong>${num(Math.abs(real.variacion_real_pct))}% real</strong> en enero–agosto. La caja del Sector Público Nacional cerró enero–julio con <strong>${money(cash.enero_julio_2026)} de ${cash.enero_julio_2026<0?'déficit':'superávit'}</strong>.</p></div><div class="management-links"><a href="#caja">Cómo cierra la caja →</a><a href="#deuda-nacional">Deuda y vencimientos →</a><a href="#provincias-nacion">Qué llega a las provincias →</a></div>`;
  }
  function renderExecution(){
    const t=D.execution.total,r=D.execution.comparison.find(r=>r.etapa==='credito_devengado');
    $('management-execution').innerHTML=`<p class="eyebrow">Gestión 2026 / Administración Nacional</p><h2 tabindex="-1">Del presupuesto al pago</h2><div class="management-stats">${stat('Pagos pendientes',money(t.devengado_menos_pagado),'Gasto reconocido menos pagado al 15/09. No identifica vencimiento.','negative')}${stat('Cambio real del gasto',pct(r.variacion_real_pct),'Enero–agosto contra los mismos meses de 2025.',sign(r.variacion_real_pct))}${stat('Presupuesto ejecutado',num(t.porcentaje_ejecucion)+'%','Gasto reconocido sobre presupuesto vigente al 15/09.')}</div><p class="editorial">Por cada $100 autorizados se reconocieron gastos por $${num(t.porcentaje_ejecucion)}. Una parte todavía espera su pago. El gasto creció en pesos, pero al descontar la inflación compró ${num(Math.abs(r.variacion_real_pct))}% ${r.variacion_real_pct<0?'menos':'más'} que un año atrás.</p>${table(['Etapa','Monto'],[['Inicial',money(t.credito_presupuestado)],['Vigente: lo autorizado hoy',money(t.credito_vigente)],['Comprometido: gasto reservado',money(t.credito_comprometido)],['Devengado: obligación reconocida',money(t.credito_devengado)],['Pagado: dinero desembolsado',money(t.credito_pagado)]],'15/09/2026 · Pesos corrientes · Etapas del mismo gasto: no se suman')}<div class="management-filters"><label>Apertura<select id="management-group"><option value="funcion">Funciones</option><option value="jurisdiccion">Organismos</option><option value="objeto">Tipo de gasto</option><option value="territorio">Ubicación</option><option value="programa">Programas</option></select></label><label>Buscar<input id="management-search" type="search" placeholder="Salud, universidad, organismo…"></label></div><div id="management-stage-table"></div>${source('gasto_etapas_total')}`;
    const old=$('ejecucion').querySelector('h2:not(#management-execution h2)');if(old){old.textContent='El ritmo del gasto, mes a mes';old.previousElementSibling.hidden=true;}
    $('management-group').onchange=stageTable;$('management-search').oninput=stageTable;stageTable();

  }
  function stageTable(){
    const kind=$('management-group').value,q=fold($('management-search').value),fields={funcion:'funcion_desc',jurisdiccion:'jurisdiccion_desc',objeto:'inciso_desc',territorio:'ubicacion_geografica_desc',programa:'programa_desc'},all=D.execution.groups[kind].filter(r=>fold([r[fields[kind]],r.servicio_desc,r.jurisdiccion_desc].join(' ')).includes(q)).sort((a,b)=>b.credito_devengado-a.credito_devengado),rows=all.slice(0,kind==='programa'?30:100);
    $('management-stage-table').innerHTML=table(['Área','Vigente','Devengado','Pagado',kind==='funcion'?'Cambio real ene–ago':'% ejecutado'],rows.map(r=>[esc(r[fields[kind]])+(kind==='programa'?`<small class="note">${esc(r.servicio_desc)}</small>`:''),money(r.credito_vigente),money(r.credito_devengado),money(r.credito_pagado),kind==='funcion'?cell(D.execution.functions_comparison.find(c=>c.finalidad_id===r.finalidad_id&&c.funcion_id===r.funcion_id)?.credito_devengado_variacion_real_pct,pct):num(M.ratio(r.credito_devengado,r.credito_vigente))+'%']),`Montos al 15/09 · Pesos corrientes · ${rows.length} de ${all.length} registros`)+source('gasto_etapas_'+kind)+(kind==='territorio'?'<p class="note">Gasto localizado: no equivale a transferencias al gobierno provincial.</p>':'');
  }
  const cashLabels={ingresos_totales:'Ingresos totales',ingresos_tributarios:'Impuestos',rentas_propiedad:'Rentas de la propiedad',otros_ingresos_corrientes:'Otros ingresos corrientes',ingresos_capital:'Ingresos de capital',gasto_primario:'Gasto antes de intereses',prestaciones_sociales:'Jubilaciones y prestaciones sociales',subsidios_economicos:'Subsidios económicos',funcionamiento_y_otros:'Funcionamiento y otros',transferencias_corrientes_provincias:'Transferencias corrientes a provincias',universidades:'Universidades',otros_gastos_corrientes:'Otros gastos corrientes',gasto_capital:'Gasto de capital',resultado_primario:'Resultado antes de intereses',intereses_netos:'Intereses',resultado_financiero:'Resultado después de intereses'};
  function renderCash(){
    const rows=D.cash.comparison,find=k=>rows.find(r=>r.indicador===k),v=k=>M.cashValue(find(k),2026,price),result=v('resultado_financiero');
    $('caja-content').innerHTML=`<h2 tabindex="-1">Cómo cierra la caja</h2><p class="note">Sector Público Nacional · Base caja · Enero–julio 2026 · ${unit()}</p><div class="management-stats">${stat('Ingresos',money(v('ingresos_totales')),'Recursos cobrados en el período.')}${stat('Gasto antes de intereses',money(v('gasto_primario')),'Pagos por funcionamiento, prestaciones e inversión.')}${stat('Resultado final',money(result),'Después de pagar intereses.',sign(result))}</div><p class="editorial">Los ingresos ${result>=0?'alcanzaron':'no alcanzaron'} para cubrir el gasto y los intereses. Antes de intereses quedaron ${money(v('resultado_primario'))}; los intereses absorbieron ${money(v('intereses_netos'))}. En términos reales, los ingresos cayeron ${num(Math.abs(find('ingresos_totales').variacion_real_acumulada_pct))}% y el gasto primario ${num(Math.abs(find('gasto_primario').variacion_real_acumulada_pct))}%. Esa diferencia achica el margen de la caja.</p>${table(['Concepto','2025','2026','Cambio real'],rows.map(r=>[esc(cashLabels[r.indicador]),cell(M.cashValue(r,2025,price),money),cell(M.cashValue(r,2026,price),money),r.indicador.startsWith('resultado_')?cell(r.cambio_real_acumulado_millones,money):cell(r.variacion_real_acumulada_pct,pct)]),`Enero–julio · ${unit()} · En los resultados, el cambio se expresa en pesos de agosto 2026`)}<p class="note">Las filas incluyen totales y componentes. Las transferencias a provincias y otros gastos corrientes tuvieron una reclasificación: su comparación real individual sigue pendiente.</p><h3>Cómo fue cerrando cada mes</h3>${bars(D.cash.monthly.filter(r=>r.indicador==='resultado_financiero'&&r.periodo.startsWith('2026')).map(r=>({name:period(r.periodo),value:price==='real'?r.real_agosto2026:r.nominal_millones})))}${source('resultado_fiscal_comparacion')}<h3>Los recursos registrados en el presupuesto</h3><p>Esta apertura corresponde a la Administración Nacional. Permite seguir qué tipos de recursos se cobraron frente a lo previsto.</p>${table(['Recurso','Vigente','Cobrado','Cambio real'],D.resources.map(r=>[esc(r.tipo_desc),money(r.recurso_vigente),money(r.recurso_ingresado_percibido),cell(r.variacion_real_pct,pct)]),'Vigente y cobrado: pesos corrientes al 15/09 · Cambio real: enero–agosto')}<p class="note">La venta de acciones partía de una base muy baja en 2025. Por eso su variación porcentual es extraordinaria; conviene mirar también el monto cobrado.</p> ${source('recursos_mensuales_tipo')}`;
  }
  function renderDebt(){
    const rows=D.debt.monthly,r=rows.at(-1),fx=M.ratio(r.stock_moneda_extranjera,r.stock_situacion_normal),cer=M.ratio(r.stock_ajustable_cer,r.stock_moneda_local);
    $('deuda-nacional-content').innerHTML=`<h2 tabindex="-1">Cuánto se debe y cuándo hay que pagar</h2><p class="note">Administración Central · Stock y pagos hasta agosto 2026 · M = millones de dólares equivalentes.</p><div class="management-stats">${stat('Deuda bruta',usd(r.stock_bruto),'Incluye pesos convertidos a dólares por la fuente.')}${stat('En moneda extranjera',num(fx)+'%','Sobre la deuda en situación de pago normal.')}${stat('Pagos de agosto',usd(r.pagos_totales),'Capital e intereses pagados durante el mes.')}</div><p class="editorial">El stock mide cuánto se debe. Para ordenar la gestión también importa cuándo se paga y en qué moneda. El ${num(fx)}% de la deuda en situación normal está en moneda extranjera y el ${num(cer)}% de la deuda en pesos se ajusta por CER, un índice ligado a la inflación.</p><div class="management-filters"><label>Serie<select id="debt-series"><option value="stock_bruto">Stock de deuda</option><option value="pagos_totales">Pagos del mes</option></select></label><label>Desde<select id="debt-from">${[2019,2020,2021,2022,2023,2024,2025,2026].map(y=>`<option value="${y}" ${y===2026?'selected':''}>${y}</option>`).join('')}</select></label></div><div id="debt-observed"></div><h3>Por qué cambió el stock en agosto</h3>${table(['Movimiento','USD millones'],[['Transacciones netas',cell(r.transacciones_netas,v=>num(v,1))],['Ajustes de valuación',cell(r.ajustes_valuacion,v=>num(v,1))],['Ajustes de deuda elegible',cell(r.ajustes_elegible,v=>num(v,1))],['Ajustes de avales',cell(r.ajustes_avales,v=>num(v,1))],['Consolidación de deudas',cell(r.consolidacion_deudas,v=>num(v,1))],['Cambio total del stock',cell(r.variacion_stock,v=>num(v,1))]],'Movimientos del stock: no todos son deuda nueva')}<p class="note">La valuación cambia por el tipo de cambio, el CER y la capitalización de intereses. Los pagos de capital se separan de los intereses.</p>${source('deuda_stock_pagos')}<h3>Calendario publicado de capital e intereses</h3><p>Este calendario usa la deuda al <strong>31/03/2026</strong>. Sirve para ver el perfil que se conocía en ese momento; los montos pueden cambiar con emisiones, pagos y refinanciaciones posteriores.</p><div class="management-filters"><label>Ver calendario<select id="debt-schedule"><option value="monthly">Mensual: abril 2026–diciembre 2027</option><option value="annual">Anual: desde abril 2026</option></select></label></div><div id="debt-calendar"></div>${source('vencimientos_perfil_marzo2026')}`;
    const observed=()=>{const key=$('debt-series').value,filtered=rows.filter(r=>+r.periodo.slice(0,4)>=+$('debt-from').value);$('debt-observed').innerHTML=bars(filtered.map(r=>({name:period(r.periodo),value:r[key]})),usd)+table(['Mes','Stock','Capital pagado','Intereses pagados'],filtered.map(r=>[period(r.periodo),num(r.stock_bruto,0),num(r.capital_pagado,0),num(r.intereses_pagados,0)]),'USD millones equivalentes · Observaciones mensuales');};
    const calendar=()=>{const annual=$('debt-schedule').value==='annual',list=annual?D.debt.annual_schedule:D.debt.schedule;const name=r=>annual?(r.periodo==='2026'?'2026 · abril–diciembre':r.periodo==='2036/2089'?'2036–2089 · suma de 54 años':r.periodo):period(r.periodo);$('debt-calendar').innerHTML=bars(list.filter(r=>!r.agrupa_varios_anios).map(r=>({name:name(r),value:r.total_usd_millones})),usd)+table(['Período','Capital','Intereses','Total'],list.map(r=>[name(r),num(r.capital_usd_millones,0),num(r.intereses_usd_millones,0),num(r.total_usd_millones,0)]),'USD millones equivalentes · Stock al 31/03/2026');};
    $('debt-series').onchange=observed;$('debt-from').onchange=observed;$('debt-schedule').onchange=calendar;observed();calendar();
  }
  function renderProvinces(){
    $('provincias-nacion-content').innerHTML=`<h2 tabindex="-1">Qué recursos llegan a cada provincia</h2><p>Coparticipación y otros recursos nacionales, separados de las transferencias del presupuesto.</p><div class="management-filters"><label>Provincia<select id="national-province">${D.provinces.comparison.map(r=>`<option value="${r.provincia_id}" ${r.provincia_id===provinceId?'selected':''}>${esc(r.provincia)}</option>`).join('')}</select></label><label>Ranking<select id="national-province-rank"><option value="variacion_real_pct">Cambio real de recursos nacionales</option><option value="pesos_por_habitante_2026">Recursos nacionales por habitante</option><option value="ron_2026">Recursos nacionales totales</option><option value="presupuestarias_devengado">Transferencias presupuestarias</option></select></label></div><div id="national-province-reading"></div><div id="national-province-ranking"></div><h3>La evolución del distrito</h3><div id="national-province-months"></div><h3>Historia de recursos nacionales desde 2003</h3><div id="national-province-history"></div>${source('ron_provincias_mensual')}${source('transferencias_presupuestarias_provincias')}<p class="note">Por habitante: monto en pesos corrientes dividido por la proyección INDEC de población de 2026. No es el dinero recibido por cada persona. Las transferencias presupuestarias identifican a administraciones provinciales; no incluyen a los municipios ni todo el gasto nacional localizado.</p>`;
    const draw=()=>{provinceId=+$('national-province').value;provinceRank=$('national-province-rank').value;const r=D.provinces.comparison.find(r=>r.provincia_id===provinceId),key=$('national-province-rank').value,rank=M.rankProvinces(D.provinces.comparison,key);$('national-province-reading').innerHTML=`<div class="management-stats">${stat('Recursos nacionales',money(price==='real'?r.ron_real_2026:r.ron_2026),`Enero–agosto · ${unit()}`)}${stat('Cambio real',pct(r.variacion_real_pct),'Contra enero–agosto de 2025.',sign(r.variacion_real_pct))}${stat('Transferencias del presupuesto',money(r.presupuestarias_devengado),'Obligaciones reconocidas al 15/09. Pesos corrientes.')}</div><p class="editorial">En ${esc(r.provincia)}, los recursos nacionales ${r.variacion_real_pct<0?'compraron menos':'ganaron poder de compra'}: ${pct(r.variacion_real_pct)} después de descontar inflación. Esto ${r.variacion_real_pct<0?'reduce':'amplía'} el margen para financiar salarios, servicios y obras con estos fondos.</p>`;
      const formatter=key==='variacion_real_pct'?pct:key==='pesos_por_habitante_2026'?v=>'$'+num(v,0):money;
      $('national-province-ranking').innerHTML=table(['Puesto','Provincia',$('national-province-rank').selectedOptions[0].text],rank.map(x=>[String(x.rank),`${x.provincia_id===r.provincia_id?'<strong>':''}${esc(x.provincia)}${x.provincia_id===r.provincia_id?'</strong>':''}`,cell(x[key],formatter)]),key==='presupuestarias_devengado'?'24 jurisdicciones · Devengado al 15/09 · Pesos corrientes':'24 jurisdicciones · Enero–agosto 2026 · Montos y por habitante en pesos corrientes');
      $('national-province-months').innerHTML=bars(D.provinces.monthly.filter(x=>x.provincia_id===r.provincia_id&&x.periodo.startsWith('2026')).map(x=>({name:period(x.periodo),value:price==='real'?x.ron_real_agosto2026:x.ron_total})));
      $('national-province-history').innerHTML=table(['Año','Recursos nacionales'],D.provinces.history.filter(x=>x.provincia_id===r.provincia_id).map(x=>[String(x.anio),money(x.ron_total)]),'2003–2025 · Pesos corrientes de cada año');};
    $('national-province-rank').value=provinceRank;$('national-province').onchange=draw;$('national-province-rank').onchange=draw;draw();
  }
  async function raw(name){
    if(rawCache.has(name))return rawCache.get(name);
    const response=await fetch(D.datasets[name].files.json.path);if(!response.ok)throw Error('No se pudo cargar el detalle. Volvé a entrar en esta sección.');
    const data=await response.json();rawCache.set(name,data);return data;
  }
  async function renderMetas(){
    const coverage=D.physical.coverage.find(r=>r.trimestre===quarter);
    $('metas-content').innerHTML=`<h2 tabindex="-1">Del gasto a las prestaciones</h2><p>Además de gastar, cada programa tiene que producir algo: atender personas, entregar tratamientos o realizar controles. Acá se compara lo realizado con lo previsto para el mismo período.</p><div class="management-filters"><label>Período<select id="physical-quarter"><option value="1" ${quarter===1?'selected':''}>Primer trimestre 2026</option><option value="2" ${quarter===2?'selected':''}>Segundo trimestre 2026</option></select></label><label>Buscar prestación u organismo<input id="physical-search" type="search" placeholder="Vacunas, jubilaciones, universidades…"></label></div><p class="note">${coverage.mediciones} mediciones · ${coverage.mediciones_sin_ejecucion} sin ejecución acumulada informada. Cada medición conserva su unidad y forma de acumulación.</p><p id="physical-count" role="status">Cargando prestaciones…</p><div id="physical-list" class="management-cards"></div><button id="physical-more" class="more" hidden>Ver más prestaciones ↓</button>${source('metas_fisicas_trimestre_'+quarter)}`;
    $('physical-quarter').onchange=()=>{quarter=+$('physical-quarter').value;metaLimit=12;renderMetas();};
    const requested=quarter;
    try{const rows=[...await raw('metas_fisicas_trimestre_'+requested)].sort((a,b)=>Number(M.finite(M.metaValues(b,requested).actual))-Number(M.finite(M.metaValues(a,requested).actual))); if(quarter!==requested||current!=='metas')return;
      const draw=()=>{const q=fold($('physical-search').value),filtered=rows.filter(r=>fold([r.medicion_fisica_desc,r.servicio_desc,r.programa_desc].join(' ')).includes(q));$('physical-count').textContent=`${Math.min(metaLimit,filtered.length)} de ${filtered.length} mediciones`;$('physical-list').innerHTML=filtered.slice(0,metaLimit).map(r=>{const v=M.metaValues(r,quarter),causes=r.causas.filter(c=>c.causa_desvio_comentario&&c.causa_desvio_comentario!=='-');return `<article><p class="eyebrow">${esc(r.tipo_medicion_fisica)}</p><h3>${esc(r.medicion_fisica_desc)}</h3><p>${esc(r.programa_desc)} · ${esc(r.servicio_desc)}</p><dl><div><dt>Previsto al trimestre</dt><dd>${num(v.planned)}</dd></div><div><dt>Realizado al trimestre</dt><dd>${num(v.actual)}</dd></div></dl><p class="note">${esc(r.unidad_medida_desc)} · ${esc(v.method)}.</p>${causes.length?`<details><summary>Explicación publicada por el organismo</summary>${causes.map(c=>`<p>${esc(c.causa_desvio_comentario)}</p>`).join('')}</details>`:''}</article>`;}).join('')||'<p>No hay prestaciones con esa búsqueda.</p>';$('physical-more').hidden=metaLimit>=filtered.length;};
      $('physical-search').oninput=()=>{metaLimit=12;draw();};$('physical-more').onclick=()=>{metaLimit+=12;draw();};draw();
    }catch(e){if(current==='metas')$('physical-count').textContent=e.message;}
  }
  async function renderWorks(){
    $('obras-ejecucion-content').innerHTML=`<h2 tabindex="-1">Cuánto avanzan las obras</h2><p>El dinero gastado y el avance de una obra pueden moverse a distinto ritmo. Por eso se muestran juntos, sin convertir uno en el otro.</p><p class="note">Primer trimestre 2026 · ${D.physical.works_count} aperturas de obras · ${D.physical.works_missing_physical} sin avance físico informado.</p><label for="physical-work-search">Buscar obra</label><input id="physical-work-search" type="search" placeholder="Ruta, edificio, localidad…"><p id="physical-work-count" role="status">Cargando obras…</p><div id="physical-works" class="management-cards"></div><button id="physical-work-more" class="more" hidden>Ver más obras ↓</button>${source('obras_ejecucion_fisica_financiera')}`;
    try{const rows=await raw('obras_ejecucion_fisica_financiera');if(current!=='obras-ejecucion')return;
      const draw=()=>{const q=fold($('physical-work-search').value),filtered=rows.filter(r=>fold(r.obra).includes(q)).sort((a,b)=>(b.credito_vigente_marzo2026_millones??-1)-(a.credito_vigente_marzo2026_millones??-1));$('physical-work-count').textContent=`${Math.min(workLimit,filtered.length)} de ${filtered.length} aperturas`;$('physical-works').innerHTML=filtered.slice(0,workLimit).map(r=>`<article><h3>${esc(r.obra)}</h3><dl><div><dt>Presupuesto vigente</dt><dd>${money(r.credito_vigente_marzo2026_millones)}</dd></div><div><dt>Gasto reconocido en el trimestre</dt><dd>${money(r.devengado_1t2026_millones)}</dd></div><div><dt>Avance físico del trimestre</dt><dd>${M.finite(r.ejecucion_fisica_1t2026_pct)?num(r.ejecucion_fisica_1t2026_pct)+'%':'Sin dato'}</dd></div><div><dt>Avance acumulado al cierre de 2025</dt><dd>${M.finite(r.avance_fisico_acumulado_2025_pct)?num(r.avance_fisico_acumulado_2025_pct)+'%':'Sin dato'}</dd></div></dl><p class="note">Pesos corrientes · Al 31/03/2026 · SAF ${r.servicio_id}, proyecto ${r.proyecto_id}, obra ${r.obra_id}.</p></article>`).join('')||'<p>No hay obras con esa búsqueda.</p>';$('physical-work-more').hidden=workLimit>=filtered.length;};
      $('physical-work-search').oninput=()=>{workLimit=12;draw();};$('physical-work-more').onclick=()=>{workLimit+=12;draw();};draw();
    }catch(e){if(current==='obras-ejecucion')$('physical-work-count').textContent=e.message;}
  }
  function renderHistory(){
    $('historia-ejecucion-content').innerHTML=`<h2 tabindex="-1">Qué pasó con los presupuestos desde 2007</h2><p>La diferencia entre el presupuesto inicial y el vigente muestra las modificaciones del año. El gasto reconocido permite ver cuánto se ejecutó de esa autorización final.</p><p class="note">Administración Nacional · Ejercicios cerrados 2007–2025 · ${unit()}</p>${table(['Año','Inicial','Vigente','Gasto reconocido','Ingresos cobrados','% ejecutado'],D.history.map(r=>[String(r.ejercicio_presupuestario),money(M.historyValue(r,'credito_presupuestado',price)),money(M.historyValue(r,'credito_vigente',price)),money(M.historyValue(r,'credito_devengado',price)),money(M.historyValue(r,'recurso_ingresado_percibido',price)),num(r.ejecucion_pct)+'%']),'Historia presupuestaria · Montos anuales')}<p class="note">${price==='real'?'El ajuste usa IPC promedio anual observado. La serie disponible permite calcular pesos constantes desde 2017. Los años anteriores quedan sin monto real.':'Los pesos de años distintos tienen distinto poder de compra. Seleccioná constantes para comparar montos desde 2017.'} Ingresos percibidos y gasto devengado tienen criterios de registro distintos: su diferencia no se presenta como resultado de caja.</p>${source('historia_ejecucion_presupuestaria')}`;
  }
  function downloads(){
    const groups=[['Presupuesto y recaudación',['gasto_etapas_total','gasto_etapas_jurisdiccion','gasto_etapas_funcion','gasto_etapas_territorio','gasto_etapas_objeto','gasto_etapas_programa','gasto_mensual_funcion','gasto_comparacion_real_funcion','gasto_comparacion_real_total','recursos_etapas_tipo','recursos_mensuales_tipo']],['Caja y deuda',['resultado_fiscal_caja_mensual','resultado_fiscal_comparacion','deuda_stock_pagos','vencimientos_perfil_marzo2026','vencimientos_anuales_perfil_marzo2026']],['Provincias',['ron_provincias_mensual','ron_comparacion_provincias','ron_historia_oficial','ron_historia_provincias_anual','transferencias_presupuestarias_provincias']],['Prestaciones, obras e historia',['metas_fisicas_trimestre_1','metas_fisicas_trimestre_2','metas_cobertura','obras_ejecucion_fisica_financiera','historia_ejecucion_presupuestaria','ipc_observado','poblacion_proyectada']]];
    $('management-downloads').innerHTML=`<h3>Los datos de gestión, disponibles para descargar</h3><p>28 conjuntos verificados. Cada archivo conserva unidades, período y fuente. La serie de PIB con diferencias de conciliación permanece fuera de los cálculos.</p>${groups.map(([label,keys])=>`<h4>${label}</h4><ul>${keys.map(key=>`<li><a href="${D.datasets[key].files.csv.path}" download>${esc(key.replaceAll('_',' '))} ↓</a><small>${D.datasets[key].rows} registros · ${esc(D.datasets[key].unit)}</small></li>`).join('')}</ul>`).join('')}<a href="data/gestion/catalogo.json" download>Catálogo y fuentes de cada conjunto ↓</a>`;
  }
  window.addEventListener('national:state',e=>{price=e.detail.price;ready();});
  window.addEventListener('hashchange',route);
  fetch('data/gestion.json?v=20260918-gestion').then(async r=>{if(!r.ok)throw Error('No se pudieron cargar los nuevos datos de gestión.');const text=await r.text();window.nationalManagementHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text.replace(/\r\n/g,'\n')))),b=>b.toString(16).padStart(2,'0')).join('');return JSON.parse(text);}).then(data=>{D=data;window.dispatchEvent(new Event('national:management-ready'));$('management-status').hidden=true;downloads();ready();}).catch(e=>{$('management-status').innerHTML=esc(e.message)+' <a href="">Reintentar</a>';});
  route();
})();
