/* Observed 2026 management data. Never uses projected inflation for actual flows. */
(() => {
  'use strict';
  const M=window.NationalManagementMath,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,d=1)=>M.finite(v)?new Intl.NumberFormat('es-AR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v):'Sin dato';
  const pct=v=>M.finite(v)?`${v>0?'+':''}${num(v)}%`:'Sin comparación';
  const sign=v=>!M.finite(v)?'':v<0?'negative':v>0?'positive':'';
  const money=v=>{if(!M.finite(v))return 'Sin dato';const a=Math.abs(v),scale=a>=1e6?1e6:a>=1000?1000:1;return `${v<0?'−':''}$${num(a/scale,a>0&&a<1?2:1)} ${scale===1e6?'billones':scale===1000?'mil millones':'millones'}`;};
  const usd=v=>M.finite(v)?`USD ${num(v,0)} M`:'Sin dato';
  const fold=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const period=v=>{const [y,m]=v.split('-');return `${['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'][+m-1]} ${y}`;};
  const pages=[['ejecucion','Presupuesto'],['modificaciones','Cambios'],['caja','Caja'],['deuda-nacional','Deuda'],['provincias-nacion','Provincias'],['metas','Prestaciones'],['obras-ejecucion','Obras'],['historia-ejecucion','Historia']];
  let D,price='nominal',current='ejecucion',quarter=2,metaLimit=12,workLimit=12,provinceId=6,provinceRank='variacion_real_pct',modificationGroup='funcion',modificationOrder='material',modificationQuery='',modificationLimit=12;
  const rawCache=new Map();
  const physicalFilters={query:'',sector:'all',status:'all',method:'all'};
  let physicalRequest=0;
  const unit=()=>price==='real'?'Pesos de agosto de 2026':'Pesos corrientes';
  const wrapper=document.querySelector('[data-page="ejecucion"]');
  wrapper.insertAdjacentHTML('afterbegin',`<nav class="management-nav" aria-label="Explorar la gestión 2026">${pages.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><p id="management-status" role="status">Cargando los datos de gestión…</p>`);
  $('ejecucion').dataset.managementPanel='ejecucion';
  for(const [id,label] of pages.slice(1))wrapper.insertAdjacentHTML('beforeend',`<section id="${id}" class="chapter management-panel" data-management-panel="${id}" hidden><p class="eyebrow">Gestión 2026 / ${label}</p><div id="${id}-content"></div></section>`);
  $('ejecucion').insertAdjacentHTML('afterbegin','<div id="management-execution"></div>');
  $('metodo').insertAdjacentHTML('beforeend','<section id="management-downloads" class="management-downloads"></section>');
  $('inicio').insertAdjacentHTML('beforeend','<div id="management-preview" class="management-preview"></div>');
  const stat=(label,value,note,cls='')=>`<article><h3>${esc(label)}</h3><strong class="management-number ${cls}">${value}</strong><p>${esc(note)}</p></article>`;
  const table=(head,rows,caption)=>`<div class="table-wrap"><table><caption>${esc(caption)}</caption><thead><tr>${head.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map((v,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${v}</${i?'td':'th'}>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}">No hay resultados para esta búsqueda.</td></tr>`}</tbody></table></div>`;
  const cell=(v,format=num)=>`<span class="${M.finite(v)&&v<0?'negative':''}">${format(v)}</span>`;
  const source=(key)=>{const d=D.datasets[key];return `<p class="note management-source">${esc(d.scope)} · <a href="${esc(d.sources[0].url)}" target="_blank" rel="noopener">Documento oficial ↗</a> · <a href="${esc(d.files.csv.path)}" download>Descargar datos CSV ↓</a></p>`;};
  const bars=(rows,formatter=money)=>{const max=Math.max(1,...rows.filter(r=>M.finite(r.value)).map(r=>Math.abs(r.value)));return `<div class="management-bars">${rows.map(r=>`<div class="management-bar-row"><div><span>${esc(r.name)}</span><strong class="${r.value<0?'negative':''}">${formatter(r.value)}</strong></div><div class="management-track"><span style="width:${M.finite(r.value)?Math.abs(r.value)/max*100:0}%;${r.value<0?'background:var(--negative)':''}"></span></div>${r.note?`<small>${esc(r.note)}</small>`:''}</div>`).join('')}</div>`;};
  const ready=()=>{if(!D)return;route();renderExecution();preview();};
  function route(){
    const anchor=location.hash.slice(1);
    current=pages.some(([id])=>id===anchor)?anchor:'ejecucion';
    document.querySelectorAll('[data-management-panel]').forEach(e=>e.hidden=e.dataset.managementPanel!==current);
    document.querySelectorAll('.management-nav a').forEach(e=>e.setAttribute('aria-current',e.hash==='#'+current?'page':'false'));
    if(!D)return;
    ({ejecucion:renderExecution,modificaciones:renderModifications,caja:renderCash,'deuda-nacional':renderDebt,'provincias-nacion':renderProvinces,metas:renderMetas,'obras-ejecucion':renderWorks,'historia-ejecucion':renderHistory})[current]();
  }
  function preview(){
    const cash=D.cash.comparison.find(r=>r.indicador==='resultado_financiero'),real=D.execution.comparison.find(r=>r.etapa==='credito_devengado');
    $('management-preview').innerHTML=`<div><p class="eyebrow">Además del proyecto / Gestión 2026</p><h2 tabindex="-1">Qué pasa con las cuentas hoy</h2><p>El gasto ejecutado bajó <strong>${num(Math.abs(real.variacion_real_pct))}% real</strong> en enero–agosto. La caja del Sector Público Nacional cerró enero–julio con <strong>${money(cash.enero_julio_2026)} de ${cash.enero_julio_2026<0?'déficit':'superávit'}</strong>.</p></div><div class="management-links"><a href="#caja">Cómo cierra la caja →</a><a href="#deuda-nacional">Deuda y vencimientos →</a><a href="#provincias-nacion">Qué llega a las provincias →</a></div>`;
  }
  function renderExecution(){
    const t=D.execution.total,r=D.execution.comparison.find(r=>r.etapa==='credito_devengado');
    $('management-execution').innerHTML=`<p class="eyebrow">Gestión 2026 / Administración Nacional</p><h2 tabindex="-1">Del presupuesto al pago</h2><div class="management-stats">${stat('Pagos pendientes',money(t.devengado_menos_pagado),'Gasto reconocido menos pagado al 15/09. No identifica vencimiento.','negative')}${stat('Cambio real del gasto',pct(r.variacion_real_pct),'Enero–agosto contra los mismos meses de 2025.',sign(r.variacion_real_pct))}${stat('Presupuesto ejecutado',num(t.porcentaje_ejecucion)+'%','Gasto reconocido sobre presupuesto vigente al 15/09.')}</div><p class="editorial">Por cada $100 autorizados se reconocieron gastos por $${num(t.porcentaje_ejecucion)}. Una parte todavía espera su pago. El gasto creció en pesos, pero al descontar la inflación compró ${num(Math.abs(r.variacion_real_pct))}% ${r.variacion_real_pct<0?'menos':'más'} que un año atrás.</p>${table(['Etapa','Monto'],[['Inicial',money(t.credito_presupuestado)],['Vigente: lo autorizado hoy',money(t.credito_vigente)],['Comprometido: gasto reservado',money(t.credito_comprometido)],['Devengado: obligación reconocida',money(t.credito_devengado)],['Pagado: dinero desembolsado',money(t.credito_pagado)]],'15/09/2026 · Pesos corrientes · Etapas del mismo gasto: no se suman')}<div class="management-filters"><label>Apertura<select id="management-group"><option value="funcion">Funciones</option><option value="jurisdiccion">Organismos</option><option value="objeto">Tipo de gasto</option><option value="territorio">Ubicación</option><option value="programa">Programas</option></select></label><label>Buscar<input id="management-search" type="search" placeholder="Salud, universidad, organismo…"></label></div><div id="management-stage-table"></div>${source('gasto_etapas_total')}`;
    const old=$('ejecucion').querySelector('h2:not(#management-execution h2)');if(old){old.textContent='El ritmo del gasto, mes a mes';old.previousElementSibling.hidden=true;}
    $('management-group').onchange=stageTable;$('management-search').oninput=stageTable;stageTable();

  }
  function stageTable(){
    const kind=$('management-group').value,q=fold($('management-search').value),fields={funcion:'funcion_desc',jurisdiccion:'jurisdiccion_desc',objeto:'inciso_desc',territorio:'ubicacion_geografica_desc',programa:'programa_desc'},all=D.execution.groups[kind].filter(r=>fold([r[fields[kind]],r.servicio_desc,r.jurisdiccion_desc].join(' ')).includes(q)).sort((a,b)=>b.credito_devengado-a.credito_devengado),rows=all.slice(0,kind==='programa'?30:100);
    $('management-stage-table').innerHTML=table(['Área','Vigente','Devengado','Pagado',kind==='funcion'?'Cambio real ene–ago':'% ejecutado'],rows.map(r=>[esc(r[fields[kind]])+(kind==='programa'?`<small class="note">${esc(r.servicio_desc)}</small>`:''),money(r.credito_vigente),money(r.credito_devengado),money(r.credito_pagado),kind==='funcion'?cell(D.execution.functions_comparison.find(c=>c.finalidad_id===r.finalidad_id&&c.funcion_id===r.funcion_id)?.credito_devengado_variacion_real_pct,pct):num(M.ratio(r.credito_devengado,r.credito_vigente))+'%']),`Montos al 15/09 · Pesos corrientes · ${rows.length} de ${all.length} registros`)+source('gasto_etapas_'+kind)+(kind==='territorio'?'<p class="note">Gasto localizado: no equivale a transferencias al gobierno provincial.</p>':'');
  }
  const cashLabels={ingresos_totales:'Ingresos totales',ingresos_tributarios:'Impuestos',rentas_propiedad:'Rentas de la propiedad',otros_ingresos_corrientes:'Otros ingresos corrientes',ingresos_capital:'Ingresos de capital',gasto_primario:'Gasto antes de intereses',prestaciones_sociales:'Jubilaciones y prestaciones sociales',subsidios_economicos:'Subsidios económicos',funcionamiento_y_otros:'Funcionamiento y otros',transferencias_corrientes_provincias:'Transferencias corrientes a provincias',universidades:'Universidades',otros_gastos_corrientes:'Otros gastos corrientes',gasto_capital:'Gasto de capital',resultado_primario:'Resultado antes de intereses',intereses_netos:'Intereses',resultado_financiero:'Resultado después de intereses'};
  function renderCash(){
    const rows=D.cash.comparison,find=k=>rows.find(r=>r.indicador===k),v=k=>M.cashValue(find(k),2026,price),result=v('resultado_financiero');
    $('caja-content').innerHTML=`<h2 tabindex="-1">Cómo cierra la caja</h2><p class="note">Sector Público Nacional · Base caja · Enero–julio 2026 · ${unit()}</p><div class="management-stats">${stat('Ingresos',money(v('ingresos_totales')),'Recursos cobrados en el período.')}${stat('Gasto antes de intereses',money(v('gasto_primario')),'Pagos por funcionamiento, prestaciones e inversión.')}${stat('Resultado final',money(result),'Después de pagar intereses.',sign(result))}</div><p class="editorial">Los ingresos ${result>=0?'alcanzaron':'no alcanzaron'} para cubrir el gasto y los intereses. Antes de intereses quedaron ${money(v('resultado_primario'))}; los intereses absorbieron ${money(v('intereses_netos'))}. En términos reales, los ingresos cayeron ${num(Math.abs(find('ingresos_totales').variacion_real_acumulada_pct))}% y el gasto primario ${num(Math.abs(find('gasto_primario').variacion_real_acumulada_pct))}%. Esa diferencia achica el margen de la caja.</p>${table(['Concepto','2025','2026','Cambio real'],rows.map(r=>[esc(cashLabels[r.indicador]),cell(M.cashValue(r,2025,price),money),cell(M.cashValue(r,2026,price),money),r.indicador.startsWith('resultado_')?cell(r.cambio_real_acumulado_millones,money):cell(r.variacion_real_acumulada_pct,pct)]),`Enero–julio · ${unit()} · En los resultados, el cambio se expresa en pesos de agosto 2026`)}<p class="note">Las filas incluyen totales y componentes. Las transferencias a provincias y otros gastos corrientes tuvieron una reclasificación: su comparación real individual sigue pendiente.</p><h3>Cómo fue cerrando cada mes</h3>${bars(D.cash.monthly.filter(r=>r.indicador==='resultado_financiero'&&r.periodo.startsWith('2026')).map(r=>({name:period(r.periodo),value:price==='real'?r.real_agosto2026:r.nominal_millones})))}${source('resultado_fiscal_comparacion')}<h3>Los recursos registrados en el presupuesto</h3><p>Esta apertura corresponde a la Administración Nacional. Permite seguir qué tipos de recursos se cobraron frente a lo previsto.</p>${table(['Recurso','Vigente','Cobrado','Cambio real'],D.resources.map(r=>[esc(r.tipo_desc),money(r.recurso_vigente),money(r.recurso_ingresado_percibido),cell(r.variacion_real_pct,pct)]),'Vigente y cobrado: pesos corrientes al 15/09 · Cambio real: enero–agosto')}<p class="note">La venta de acciones partía de una base muy baja en 2025. Por eso su variación porcentual es extraordinaria; conviene mirar también el monto cobrado.</p> ${source('recursos_mensuales_tipo')}`;
  }
  const evidenceSource=name=>D.updates.sources.find(s=>s.path.endsWith('/'+name));
  function recentDebt(){
    const d=D.updates.debt,s=evidenceSource(d.source);
    return `<section class="recent-debt"><p class="eyebrow">Perfil actualizado / Corte al 31 de julio</p><h3>Cómo se repartían los pagos de agosto a diciembre</h3><p>La mayor concentración en pesos estaba en diciembre. En moneda extranjera, en septiembre. Son capital e intereses proyectados al 31/07; las emisiones y los canjes posteriores pueden cambiar esos montos.</p><div class="debt-currency-panels"><article><h4>Pagaderos en pesos</h4><strong class="management-number">${money(d.totals.ars_thousand_millions*1000)}</strong>${bars(d.months.map(r=>({name:period(r.period),value:r.ars_thousand_millions*1000})))}</article><article><h4>Pagaderos en moneda extranjera</h4><strong class="management-number">${usd(d.totals.fx_usd_millions)}</strong>${bars(d.months.map(r=>({name:period(r.period),value:r.fx_usd_millions})),usd)}</article></div><p class="note">${num(M.ratio(d.fmi_usd_millions,d.totals.fx_usd_millions))}% de los pagos en moneda extranjera corresponde al FMI. Pesos corrientes y USD equivalentes se muestran por separado. Incluye agosto; los totales conservan el redondeo de la fuente.</p><p class="note management-source">OPC · Informe del 10/09/2026 · Cuadro 7 · <a href="${s.path}#page=${d.pdf_page}" target="_blank" rel="noopener">Ver documento oficial ↗</a></p></section>`;
  }
  function modificationTimeline(){
    const m=D.updates.modifications;
    return `<section id="modification-timeline"><p><a class="button" href="#normas">Ver qué modificó cada norma →</a></p><h3>Las normas que cambiaron el monto total</h3><ol class="norm-timeline">${m.acts.map(r=>{const s=evidenceSource(r.source);return `<li><div><span>${r.date.split('-').reverse().join('/')} · <a href="${s.path}#page=${r.pdf_page}" target="_blank" rel="noopener">${esc(r.title)}</a></span><strong class="${r.spending_ars_millions<0?'negative':''}">${r.spending_ars_millions>0?'+':''}${money(r.spending_ars_millions)}</strong></div><p>${esc(r.reading)}</p></li>`;}).join('')}</ol><p class="note">Cambios del gasto autorizado, en pesos corrientes. La suma coincide con el cambio neto del tablero dentro del redondeo de los informes. Fuente: Oficina de Presupuesto del Congreso y <a href="${m.index_url}" target="_blank" rel="noopener">registro oficial de normas</a>. Las reasignaciones dentro del total requieren un seguimiento por partida.</p></section>`;
  }
  function renderDebt(){
    const rows=D.debt.monthly,r=rows.at(-1),fx=M.ratio(r.stock_moneda_extranjera,r.stock_situacion_normal),cer=M.ratio(r.stock_ajustable_cer,r.stock_moneda_local);
    $('deuda-nacional-content').innerHTML=`<h2 tabindex="-1">Cuánto se debe y cuándo hay que pagar</h2><p class="note">Administración Central · Stock y pagos hasta agosto 2026 · M = millones de dólares equivalentes.</p><div class="management-stats">${stat('Deuda bruta',usd(r.stock_bruto),'Incluye pesos convertidos a dólares por la fuente.')}${stat('En moneda extranjera',num(fx)+'%','Sobre la deuda en situación de pago normal.')}${stat('Pagos de agosto',usd(r.pagos_totales),'Capital e intereses pagados durante el mes.')}</div><p class="editorial">El stock mide cuánto se debe. Para ordenar la gestión también importa cuándo se paga y en qué moneda. El ${num(fx)}% de la deuda en situación normal está en moneda extranjera y el ${num(cer)}% de la deuda en pesos se ajusta por CER, un índice ligado a la inflación.</p>${recentDebt()}<h3>Stock y pagos realizados</h3><div class="management-filters"><label>Serie<select id="debt-series"><option value="stock_bruto">Stock de deuda</option><option value="pagos_totales">Pagos del mes</option></select></label><label>Desde<select id="debt-from">${[2019,2020,2021,2022,2023,2024,2025,2026].map(y=>`<option value="${y}" ${y===2026?'selected':''}>${y}</option>`).join('')}</select></label></div><div id="debt-observed"></div><h3>Por qué cambió el stock en agosto</h3>${table(['Movimiento','USD millones'],[['Transacciones netas',cell(r.transacciones_netas,v=>num(v,1))],['Ajustes de valuación',cell(r.ajustes_valuacion,v=>num(v,1))],['Ajustes de deuda elegible',cell(r.ajustes_elegible,v=>num(v,1))],['Ajustes de avales',cell(r.ajustes_avales,v=>num(v,1))],['Consolidación de deudas',cell(r.consolidacion_deudas,v=>num(v,1))],['Cambio total del stock',cell(r.variacion_stock,v=>num(v,1))]],'Movimientos del stock: no todos son deuda nueva')}<p class="note">La valuación cambia por el tipo de cambio, el CER y la capitalización de intereses. Los pagos de capital se separan de los intereses.</p>${source('deuda_stock_pagos')}<h3>Perfil de largo plazo / Corte a marzo</h3><p>Este calendario usa la deuda al <strong>31/03/2026</strong>. Sirve para ver el perfil que se conocía en ese momento; los montos pueden cambiar con emisiones, pagos y refinanciaciones posteriores.</p><div class="management-filters"><label>Ver calendario<select id="debt-schedule"><option value="monthly">Mensual: abril 2026–diciembre 2027</option><option value="annual">Anual: desde abril 2026</option></select></label></div><div id="debt-calendar"></div>${source('vencimientos_perfil_marzo2026')}`;
    const observed=()=>{const key=$('debt-series').value,filtered=rows.filter(r=>+r.periodo.slice(0,4)>=+$('debt-from').value);$('debt-observed').innerHTML=bars(filtered.map(r=>({name:period(r.periodo),value:r[key]})),usd)+table(['Mes','Stock','Capital pagado','Intereses pagados'],filtered.map(r=>[period(r.periodo),num(r.stock_bruto,0),num(r.capital_pagado,0),num(r.intereses_pagados,0)]),'USD millones equivalentes · Observaciones mensuales');};
    const calendar=()=>{const annual=$('debt-schedule').value==='annual',list=annual?D.debt.annual_schedule:D.debt.schedule;const name=r=>annual?(r.periodo==='2026'?'2026 · abril–diciembre':r.periodo==='2036/2089'?'2036–2089 · suma de 54 años':r.periodo):period(r.periodo);$('debt-calendar').innerHTML=bars(list.filter(r=>!r.agrupa_varios_anios).map(r=>({name:name(r),value:r.total_usd_millones})),usd)+table(['Período','Capital','Intereses','Total'],list.map(r=>[name(r),num(r.capital_usd_millones,0),num(r.intereses_usd_millones,0),num(r.total_usd_millones,0)]),'USD millones equivalentes · Stock al 31/03/2026');};
    $('debt-series').onchange=observed;$('debt-from').onchange=observed;$('debt-schedule').onchange=calendar;observed();calendar();
  }
  function renderModifications(){
    const t=D.execution.total,net=M.delta(t.credito_vigente,t.credito_presupuestado);
    $('modificaciones-content').innerHTML=`<h2 tabindex="-1">Cómo cambió el presupuesto de 2026</h2>
      <p>El presupuesto inicial fue el punto de partida. Las modificaciones lo ampliaron o redujeron hasta llegar a la autorización vigente.</p>
      <div class="management-stats">${stat('Inicial',money(t.credito_presupuestado),'Autorizado al comenzar 2026.')}${stat('Cambio neto',money(net),pct(M.change(t.credito_vigente,t.credito_presupuestado))+' sobre el inicial.',sign(net))}${stat('Vigente',money(t.credito_vigente),'Autorizado al 15/09/2026.')}</div>
      <p class="editorial">La autorización total ${net<0?'se redujo':'aumentó'} ${money(Math.abs(net))}. El cambio de cada área permite ver dónde quedaron más o menos recursos. Son montos en pesos corrientes: una ampliación no demuestra, por sí sola, que haya ganado poder de compra.</p>${modificationTimeline()}<h3>Qué cambió en cada área</h3>
      <div class="management-filters"><label>Apertura<select id="modification-group"><option value="funcion">Funciones</option><option value="programa">Programas</option><option value="jurisdiccion">Organismos</option><option value="objeto">Tipo de gasto</option></select></label><label>Ordenar<select id="modification-order"><option value="material">Mayores cambios en pesos</option><option value="increase">Ampliaciones</option><option value="reduction">Reducciones</option></select></label><label>Buscar<input id="modification-search" type="search" placeholder="Vacunas, universidades, jubilaciones…"></label></div>
      <p id="modification-balance" class="note"></p><p id="modification-count" role="status"></p><div id="modification-list" class="management-cards modification-cards"></div><button id="modification-more" class="more">Ver más cambios ↓</button>
      <p class="note">Comparación dentro de 2026 y de la clasificación publicada al 15/09. Cada cambio por área es neto: no se asigna a una norma individual sin su correspondencia documental. Un traslado entre organismos no se interpreta automáticamente como un recorte o una política nueva.</p><div id="modification-source"></div>`;
    $('modification-group').value=modificationGroup;$('modification-order').value=modificationOrder;$('modification-search').value=modificationQuery;
    const draw=()=>{
      const labels={funcion:'funcion_desc',programa:'programa_desc',jurisdiccion:'jurisdiccion_desc',objeto:'inciso_desc'};
      const all=M.modifications(D.execution.groups[modificationGroup]),balance=M.modificationBalance(all),q=modificationQuery;
      const rows=all.filter(r=>window.BudgetMath.matchesSearch({name:r[labels[modificationGroup]],entity:r.servicio_desc,jurisdiction:r.jurisdiccion_desc},q)).filter(r=>modificationOrder==='increase'?r.modification>0:modificationOrder==='reduction'?r.modification<0:true).sort((a,b)=>modificationOrder==='increase'?b.modification-a.modification:modificationOrder==='reduction'?a.modification-b.modification:Math.abs(b.modification)-Math.abs(a.modification));
      $('modification-balance').innerHTML=`En esta apertura, las ampliaciones suman ${money(balance.increases)} y las reducciones <span class="negative">${money(balance.reductions)}</span>. El saldo es ${money(balance.net)}. Los movimientos dentro de una misma área pueden compensarse.`;
      $('modification-count').textContent=`${Math.min(modificationLimit,rows.length)} de ${rows.length} resultados · Pesos corrientes`;
      $('modification-list').innerHTML=rows.slice(0,modificationLimit).map(r=>`<article><h3>${esc(r[labels[modificationGroup]])}</h3>${modificationGroup==='programa'?`<p>${esc(r.servicio_desc)} · ${esc(r.jurisdiccion_desc)}</p>`:''}<strong class="management-number ${sign(r.modification)}">${money(r.modification)}</strong><p>${M.finite(r.modification_pct)?pct(r.modification_pct)+' frente al inicial.':r.credito_presupuestado===0?'Sin base inicial positiva para calcular un porcentaje.':'Sin comparación porcentual.'}</p><dl><div><dt>Inicial</dt><dd>${money(r.credito_presupuestado)}</dd></div><div><dt>Vigente</dt><dd>${money(r.credito_vigente)}</dd></div></dl></article>`).join('')||'<p>No hay partidas con esos filtros.</p>';
      $('modification-more').hidden=modificationLimit>=rows.length;$('modification-source').innerHTML=source('gasto_etapas_'+modificationGroup);
    };
    $('modification-group').onchange=e=>{modificationGroup=e.target.value;modificationLimit=12;draw();};
    $('modification-order').onchange=e=>{modificationOrder=e.target.value;modificationLimit=12;draw();};
    $('modification-search').oninput=e=>{modificationQuery=e.target.value;modificationLimit=12;draw();};
    $('modification-more').onclick=()=>{modificationLimit+=24;draw();};draw();
  }
  function renderProvinces(){
    const B=window.nationalBudgetContext?.data;
    if(!B){$('provincias-nacion-content').textContent='Cargando la ficha provincial…';return;}
    const requested=Number(new URLSearchParams(location.search).get('distrito'));
    if(D.provinces.comparison.some(r=>r.provincia_id===requested))provinceId=requested;
    $('provincias-nacion-content').innerHTML=`<h2 tabindex="-1">Nación en cada provincia</h2><p>Qué recursos recibe el gobierno provincial, qué gasto registra Nación en el territorio y qué propone para 2027.</p>
      <div class="management-filters"><label>Provincia<select id="national-province">${D.provinces.comparison.map(r=>`<option value="${r.provincia_id}" ${r.provincia_id===provinceId?'selected':''}>${esc(r.provincia)}</option>`).join('')}</select></label></div>
      <div class="decision-links"><button id="copy-national-province" class="button button-quiet">Copiar enlace</button><button class="button" data-export-focus="provincia">Exportar ficha provincial</button></div>
      <div id="national-province-reading"></div><div id="national-province-integrated"></div>
      <h3>Las 24 jurisdicciones, en comparación</h3><label>Ranking<select id="national-province-rank"><option value="variacion_real_pct">Cambio real de recursos nacionales</option><option value="pesos_por_habitante_2026">Recursos nacionales por habitante</option><option value="ron_2026">Recursos nacionales totales</option><option value="presupuestarias_devengado">Transferencias presupuestarias</option></select></label><div id="national-province-ranking"></div>
      <h3>La evolución del distrito</h3><div id="national-province-months"></div><h3>Historia de recursos nacionales desde 2003</h3><div id="national-province-history"></div>
      ${source('ron_provincias_mensual')}${source('transferencias_presupuestarias_provincias')}${source('gasto_etapas_territorio')}
      <p class="note">Por habitante: recursos nacionales en pesos corrientes divididos por la proyección INDEC de población de 2026. No es un pago a cada persona. Las transferencias identifican administraciones provinciales; el gasto localizado también incluye jubilaciones, salarios y otros servicios nacionales.</p>`;
    const draw=()=>{
      provinceId=+$('national-province').value;provinceRank=$('national-province-rank').value;
      const model=M.territory(B,D,provinceId);if(!model){$('national-province-reading').textContent='No se pudo verificar la correspondencia de esta provincia.';return;}
      const {province:r,project:g,observed:o,works,worksTotal,pending}=model;
      $('national-province-reading').innerHTML=`<h3 class="territory-title">${esc(r.provincia)}</h3><div class="management-stats">${stat('Recursos nacionales',money(price==='real'?r.ron_real_2026:r.ron_2026),`Enero–agosto · ${unit()}`)}${stat('Cambio real',pct(r.variacion_real_pct),'Contra enero–agosto de 2025.',sign(r.variacion_real_pct))}${stat('Transferencias pagadas',money(r.presupuestarias_pagado),'Del presupuesto al gobierno provincial · al 15/09 · pesos corrientes.')}</div>
        <p class="editorial">En ${esc(r.provincia)}, los recursos nacionales ${r.variacion_real_pct<0?'perdieron':'ganaron'} ${num(Math.abs(r.variacion_real_pct))}% de poder de compra. Eso ${r.variacion_real_pct<0?'achica':'amplía'} el margen para sostener servicios con estos fondos. En las transferencias presupuestarias, ${money(pending)} de obligaciones reconocidas todavía no figuran pagadas.</p>`;
      const src=B.sources.find(s=>s.file===g.source),workSrc=B.sources.find(s=>s.file==='cap1pl12.pdf');
      const comps=window.BudgetMath.comparisonRows(g,B.deflator.annual_factors).filter(x=>x.base!=='law');
      const top=works.slice(0,5),workLink=new URL(location.href);workLink.search='';workLink.searchParams.set('provincia',r.provincia);workLink.hash='obras';
      $('national-province-integrated').innerHTML=`<div class="territory-blocks">
        <article><p class="eyebrow">2026 / Gobierno provincial</p><h3>Las transferencias del presupuesto</h3><dl class="work-facts"><div><dt>Gasto reconocido</dt><dd>${money(r.presupuestarias_devengado)}</dd></div><div><dt>Dinero pagado</dt><dd>${money(r.presupuestarias_pagado)}</dd></div><div><dt>Pendiente de pago</dt><dd class="${pending>0?'negative':''}">${money(pending)}</dd></div></dl><p class="note">Al 15/09 · Pesos corrientes. Pendiente de pago no identifica qué parte está vencida.</p></article>
        <article><p class="eyebrow">2026 / Territorio</p><h3>El gasto nacional localizado</h3><strong class="management-number">${money(o.credito_devengado)}</strong><p>Gasto reconocido al 15/09 sobre ${money(o.credito_vigente)} autorizados: ${num(M.ratio(o.credito_devengado,o.credito_vigente))}% ejecutado.</p><p class="note">Pesos corrientes. Incluye gasto directo de Nación y transferencias: no se suma a los fondos provinciales.</p></article></div>
        <section class="territory-project"><p class="eyebrow">Proyecto 2027 / Territorio</p><h3>Qué propone Nación para ${esc(r.provincia)}</h3><strong class="management-number">${money(g.project)}</strong><p>Gasto localizado propuesto en pesos corrientes. Es presupuesto nacional, no el presupuesto de la provincia.</p>
        ${table(['Base 2026','Cambio en pesos','Cambio real'],comps.map(c=>[c.base==='current'?'Vigente al 15/09':'Cierre estimado',cell(c.nominal,pct),cell(c.real,pct)]),'Comparación del proyecto 2027 · Real: ajustado por el escenario de inflación promedio anual')}
        <h3>${works.length} partidas de inversión</h3><p>Suman ${money(worksTotal)} dentro del gasto propuesto. Estas son las ${Math.min(top.length,5)} de mayor monto; una obra puede aparecer en varias ubicaciones.</p>
        <div class="territory-work-list">${top.map(w=>`<article><h4>${esc(w.name)}</h4><strong>${money(w.project)}</strong><p>${esc(w.entity)}</p>${w.id==='w101'?'<a href="#obra-ra10">Ver continuidad y avance del RA-10 →</a>':''}</article>`).join('')||'<p>Esta ubicación no tiene partidas en la planilla de inversión consultada.</p>'}</div>
        <div class="decision-links"><a href="${esc(workLink.href)}">Ver todas las partidas y su financiamiento →</a><a href="${esc(src.url)}#page=${g.page}" target="_blank" rel="noopener">Distribución oficial ↗</a><a href="${esc(workSrc.url)}" target="_blank" rel="noopener">Planilla de inversión ↗</a></div></section>`;
      const formatter=provinceRank==='variacion_real_pct'?pct:provinceRank==='pesos_por_habitante_2026'?v=>'$'+num(v,0):money;
      $('national-province-ranking').innerHTML=table(['Puesto','Provincia',$('national-province-rank').selectedOptions[0].text],M.rankProvinces(D.provinces.comparison,provinceRank).map(x=>[String(x.rank),`${x.provincia_id===r.provincia_id?'<strong>':''}${esc(x.provincia)}${x.provincia_id===r.provincia_id?'</strong>':''}`,cell(x[provinceRank],formatter)]),provinceRank==='presupuestarias_devengado'?'24 jurisdicciones · Devengado al 15/09 · Pesos corrientes':'24 jurisdicciones · Enero–agosto 2026 · Montos y por habitante en pesos corrientes');
      $('national-province-months').innerHTML=bars(D.provinces.monthly.filter(x=>x.provincia_id===r.provincia_id&&x.periodo.startsWith('2026')).map(x=>({name:period(x.periodo),value:price==='real'?x.ron_real_agosto2026:x.ron_total})));
      $('national-province-history').innerHTML=table(['Año','Recursos nacionales'],D.provinces.history.filter(x=>x.provincia_id===r.provincia_id).map(x=>[String(x.anio),money(x.ron_total)]),'2003–2025 · Pesos corrientes de cada año');
      // Short comparison tables become labeled rows on phones.
      document.querySelectorAll('.territory-project table').forEach(t=>{t.classList.add('territory-table');const heads=[...t.querySelectorAll('thead th')].map(x=>x.textContent);t.querySelectorAll('tbody tr').forEach(row=>[...row.children].forEach((c,i)=>c.dataset.label=heads[i]));});
    };
    $('national-province-rank').value=provinceRank;
    $('national-province').onchange=()=>{const u=new URL(location.href);u.searchParams.set('distrito',$('national-province').value);history.replaceState(null,'',u);draw();};
    $('national-province-rank').onchange=draw;
    $('copy-national-province').onclick=async e=>{const u=new URL(location.href);u.searchParams.set('distrito',provinceId);u.hash='provincias-nacion';try{await navigator.clipboard.writeText(u.href);e.target.textContent='Enlace copiado';}catch(_){history.replaceState(null,'',u);e.target.textContent='Copiá la dirección del navegador';}};
    draw();
  }
  async function raw(name){
    if(rawCache.has(name))return rawCache.get(name);
    const response=await fetch(D.datasets[name].files.json.path);if(!response.ok)throw Error('No se pudo cargar el detalle. Volvé a entrar en esta sección.');
    const data=await response.json();rawCache.set(name,data);return data;
  }
  async function renderMetas(){
    const coverage=D.physical.coverage.find(r=>r.trimestre===quarter);
    $('metas-content').innerHTML=`<h2 tabindex="-1">Del gasto a las prestaciones</h2><p>Además de gastar, cada programa tiene que producir algo: atender personas, entregar tratamientos o realizar controles. Compará lo realizado con lo previsto para el mismo período.</p><div class="management-filters physical-filters"><label>Período<select id="physical-quarter"><option value="1" ${quarter===1?'selected':''}>Primer trimestre 2026</option><option value="2" ${quarter===2?'selected':''}>Segundo trimestre 2026</option></select></label><label>Buscar prestación u organismo<input id="physical-search" type="search" placeholder="Vacunas, jubilaciones, universidades…" value="${esc(physicalFilters.query)}"></label><label>Sector<select id="physical-sector"><option value="all">Todos los sectores</option></select></label><label>Comparación<select id="physical-status"><option value="all">Todas las mediciones</option><option value="below">Por debajo de lo previsto</option><option value="equal">Igual a lo previsto</option><option value="above">Por encima de lo previsto</option><option value="missing">Sin dato de realización</option><option value="uncomparable">Sin base positiva para comparar</option></select></label><label>Cómo se mide<select id="physical-method"><option value="all">Todos los métodos</option></select></label></div><button id="physical-reset" class="button button-quiet">Limpiar filtros</button><p class="note">${coverage.mediciones} mediciones · ${coverage.mediciones_sin_ejecucion} sin ejecución acumulada informada. Un desvío no indica por sí solo una mejora o un problema: depende de qué se mide.</p><p id="physical-count" role="status">Cargando prestaciones…</p><div id="physical-list" class="management-cards"></div><button id="physical-more" class="more" hidden>Ver más prestaciones ↓</button>${source('metas_fisicas_trimestre_'+quarter)}`;
    $('physical-quarter').onchange=()=>{quarter=+$('physical-quarter').value;metaLimit=12;renderMetas();};
    const requested=quarter,request=++physicalRequest;
    try{const rows=[...await raw('metas_fisicas_trimestre_'+requested)].sort((a,b)=>Number(M.finite(M.metaValues(b,requested).actual))-Number(M.finite(M.metaValues(a,requested).actual))); if(quarter!==requested||current!=='metas'||request!==physicalRequest)return;
      for(const [id,key,field] of [['sector','sector','funcion_desc'],['method','method','totalizador_avance_fisico']]){
        const options=[...new Set(rows.map(r=>r[field]))].sort((a,b)=>a.localeCompare(b,'es'));
        $('physical-'+id).insertAdjacentHTML('beforeend',options.map(v=>`<option value="${esc(v)}">${esc(id==='method'?v.split(':')[0]:v)}</option>`).join(''));
        if(!options.includes(physicalFilters[key]))physicalFilters[key]='all';
        $('physical-'+id).value=physicalFilters[key];
      }
      $('physical-status').value=physicalFilters.status;
      const draw=()=>{
        const filtered=rows.filter(r=>(physicalFilters.sector==='all'||r.funcion_desc===physicalFilters.sector)&&(physicalFilters.method==='all'||r.totalizador_avance_fisico===physicalFilters.method)&&(physicalFilters.status==='all'||M.metaStatus(r,quarter).key===physicalFilters.status)&&window.BudgetMath.matchesSearch({name:[r.medicion_fisica_desc,r.programa_desc].join(' '),entity:r.servicio_desc,jurisdiction:r.jurisdiccion_desc},physicalFilters.query));
        $('physical-count').textContent=`${Math.min(metaLimit,filtered.length)} de ${filtered.length} mediciones`;
        $('physical-list').innerHTML=filtered.slice(0,metaLimit).map(r=>{const v=M.metaValues(r,quarter),status=M.metaStatus(r,quarter),causes=r.causas.filter(c=>c.causa_desvio_comentario&&c.causa_desvio_comentario!=='-');const method={Suma:'Suma de lo realizado durante el período.',Promedio:'Promedio del período; no se suman los meses.',Stock:'Cantidad al cierre del período.',Transversal:'Medición transversal, según el criterio del organismo.'}[v.method.split(':')[0]]||v.method;
          return `<article><p class="eyebrow">${esc(r.funcion_desc)} · ${esc(r.tipo_medicion_fisica)}</p><h3>${esc(r.medicion_fisica_desc)}</h3><p>${esc(r.programa_desc)} · ${esc(r.servicio_desc)}</p><p class="physical-status">${esc(status.label)}${M.finite(status.deviation)?` · <strong class="${status.deviation<0?'negative':''}">${pct(status.deviation)}</strong>`:''}</p><dl><div><dt>Previsto al trimestre</dt><dd>${num(v.planned)}</dd></div><div><dt>Realizado al trimestre</dt><dd>${num(v.actual)}</dd></div></dl><p class="note">${esc(r.unidad_medida_desc)} · ${esc(method)}</p>${causes.length?`<details><summary>Explicación publicada por el organismo</summary>${causes.map(c=>`<p>${esc(c.causa_desvio_comentario)}</p>`).join('')}</details>`:''}</article>`;}).join('')||'<p>No hay prestaciones con esos filtros.</p>';
        $('physical-more').hidden=metaLimit>=filtered.length;
      };
      for(const [id,key] of [['search','query'],['sector','sector'],['status','status'],['method','method']])$('physical-'+id)[id==='search'?'oninput':'onchange']=e=>{physicalFilters[key]=e.target.value;metaLimit=12;draw();};
      $('physical-reset').onclick=()=>{Object.assign(physicalFilters,{query:'',sector:'all',status:'all',method:'all'});metaLimit=12;renderMetas();};
      $('physical-more').onclick=()=>{metaLimit+=12;draw();};draw();
    }catch(e){if(current==='metas'&&request===physicalRequest)$('physical-count').textContent=e.message;}
  }
  async function renderWorks(){
    $('obras-ejecucion-content').innerHTML=`<h2 tabindex="-1">Cuánto avanzan las obras</h2><p>El dinero gastado y el avance de una obra pueden moverse a distinto ritmo. Por eso se muestran juntos, sin convertir uno en el otro.</p><p class="note">Primer trimestre 2026 · ${D.physical.works_count} aperturas de obras · ${D.physical.works_missing_physical} sin avance físico informado.</p><label for="physical-work-search">Buscar obra</label><input id="physical-work-search" type="search" placeholder="Ruta, edificio, localidad…"><p id="physical-work-count" role="status">Cargando obras…</p><div id="physical-works" class="management-cards"></div><button id="physical-work-more" class="more" hidden>Ver más obras ↓</button>${source('obras_ejecucion_fisica_financiera')}`;
    try{const rows=await raw('obras_ejecucion_fisica_financiera');if(current!=='obras-ejecucion')return;
      const draw=()=>{const q=fold($('physical-work-search').value),filtered=rows.filter(r=>fold(r.obra).includes(q)).sort((a,b)=>(b.credito_vigente_marzo2026_millones??-1)-(a.credito_vigente_marzo2026_millones??-1));$('physical-work-count').textContent=`${Math.min(workLimit,filtered.length)} de ${filtered.length} aperturas`;$('physical-works').innerHTML=filtered.slice(0,workLimit).map(r=>`<article><h3>${esc(r.obra)}</h3><dl><div><dt>Presupuesto vigente</dt><dd>${money(r.credito_vigente_marzo2026_millones)}</dd></div><div><dt>Gasto reconocido en el trimestre</dt><dd>${money(r.devengado_1t2026_millones)}</dd></div><div><dt>Avance físico del trimestre</dt><dd>${M.finite(r.ejecucion_fisica_1t2026_pct)?num(r.ejecucion_fisica_1t2026_pct)+'%':'Sin dato'}</dd></div><div><dt>Avance acumulado al cierre de 2025</dt><dd>${M.finite(r.avance_fisico_acumulado_2025_pct)?num(r.avance_fisico_acumulado_2025_pct)+'%':'Sin dato'}</dd></div></dl><p class="note">Pesos corrientes · Al 31/03/2026 · SAF ${r.servicio_id}, proyecto ${r.proyecto_id}, obra ${r.obra_id}.</p></article>`).join('')||'<p>No hay obras con esa búsqueda.</p>';$('physical-work-more').hidden=workLimit>=filtered.length;};
      $('physical-work-search').oninput=()=>{workLimit=12;draw();};$('physical-work-more').onclick=()=>{workLimit+=12;draw();};draw();
    }catch(e){if(current==='obras-ejecucion')$('physical-work-count').textContent=e.message;}
  }
  function renderHistory(){
    $('historia-ejecucion-content').innerHTML=`<h2 tabindex="-1">Qué pasó con los presupuestos desde 2007</h2><p>La diferencia entre el presupuesto inicial y el vigente muestra las modificaciones del año. El gasto reconocido permite ver cuánto se ejecutó de esa autorización final.</p><p class="note">Administración Nacional · Ejercicios cerrados 2007–2025 · ${unit()}</p>${table(['Año','Inicial','Vigente','Gasto reconocido','Ingresos cobrados','% ejecutado'],D.history.map(r=>[String(r.ejercicio_presupuestario),money(M.historyValue(r,'credito_presupuestado',price)),money(M.historyValue(r,'credito_vigente',price)),money(M.historyValue(r,'credito_devengado',price)),money(M.historyValue(r,'recurso_ingresado_percibido',price)),num(r.ejecucion_pct)+'%']),'Historia presupuestaria · Montos anuales')}<p class="note">${price==='real'?'El ajuste usa IPC promedio anual observado. La serie disponible permite calcular pesos constantes desde 2017. Los años anteriores quedan sin monto real.':'Los pesos de años distintos tienen distinto poder de compra. Seleccioná constantes para comparar montos desde 2017.'} Ingresos percibidos y gasto devengado tienen criterios de registro distintos: su diferencia no se presenta como resultado de caja.</p>${source('historia_ejecucion_presupuestaria')}`;
  }
  function downloads(){
    const groups=[['Presupuesto y recaudación',['gasto_etapas_total','gasto_etapas_jurisdiccion','gasto_etapas_funcion','gasto_etapas_territorio','gasto_etapas_objeto','gasto_etapas_programa','gasto_mensual_funcion','gasto_comparacion_real_funcion','gasto_comparacion_real_total','recursos_etapas_tipo','recursos_mensuales_tipo']],['Caja y deuda',['resultado_fiscal_caja_mensual','resultado_fiscal_comparacion','deuda_stock_pagos','vencimientos_perfil_marzo2026','vencimientos_anuales_perfil_marzo2026']],['Provincias',['ron_provincias_mensual','ron_comparacion_provincias','ron_historia_oficial','ron_historia_provincias_anual','transferencias_presupuestarias_provincias']],['Prestaciones, obras e historia',['metas_fisicas_trimestre_1','metas_fisicas_trimestre_2','metas_cobertura','obras_ejecucion_fisica_financiera','historia_ejecucion_presupuestaria','ipc_observado','poblacion_proyectada']]];
    $('management-downloads').innerHTML=`<h3>Los datos de gestión, disponibles para descargar</h3><p>28 conjuntos de base y dos ampliaciones documentales. Cada archivo conserva unidades, período y fuente. La serie de PIB con diferencias de conciliación permanece fuera de los cálculos.</p>${groups.map(([label,keys])=>`<h4>${label}</h4><ul>${keys.map(key=>`<li><a href="${D.datasets[key].files.csv.path}" download>${esc(key.replaceAll('_',' '))} ↓</a><small>${D.datasets[key].rows} registros · ${esc(D.datasets[key].unit)}</small></li>`).join('')}</ul>`).join('')}<a href="data/gestion/catalogo.json" download>Catálogo y fuentes de cada conjunto ↓</a><p><a href="data/management-sources/evidence.json" download>Cronología de normas y perfil OPC de julio ↓</a></p>`;
  }
  window.addEventListener('national:state',e=>{price=e.detail.price;ready();});
  window.addEventListener('hashchange',route);
  window.addEventListener('popstate',route);
  window.addEventListener('national:budget-ready',()=>{if(D&&current==='provincias-nacion')renderProvinces();});
  fetch('data/gestion.json?v=20260918-opc').then(async r=>{if(!r.ok)throw Error('No se pudieron cargar los nuevos datos de gestión.');const text=await r.text();window.nationalManagementHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text.replace(/\r\n/g,'\n')))),b=>b.toString(16).padStart(2,'0')).join('');return JSON.parse(text);}).then(data=>{D=data;window.nationalManagementContext=D;window.dispatchEvent(new Event('national:management-ready'));$('management-status').hidden=true;downloads();ready();}).catch(e=>{$('management-status').innerHTML=esc(e.message)+' <a href="">Reintentar</a>';});
  route();
})();
