(()=>{
  'use strict';
  const $=id=>document.getElementById(id),P=window.NationalPlanning;
  const num=(v,n=1)=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:n}).format(v);
  const money=v=>`${v<0?'−':''}$${num(Math.abs(v)/1e6)} billones`;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stat=(title,value,desc,negative=false)=>`<article><h3>${title}</h3><strong class="decision-number ${negative?'negative':''}">${value}</strong><p>${desc}</p></article>`;
  const table=(heads,rows)=>`<div class="decision-table-wrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<${i?'td':'th'} ${i?'data-label="'+heads[i]+'"':'scope="row"'}>${v}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  let B,D,R,rows,state,defaults,last,loading;
  const save=(name,data,type='application/json')=>{const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function update(){
    const c=P.closing(B,rows,state),s=P.integrated(B,D,state),rev=P.revenue(R,state);
    if(!c||!s||!rev){$('planning-results').innerHTML='<p role="alert">Revisá los supuestos. Completá todos los campos dentro de los límites indicados.</p>';$('planning-export').disabled=true;return;}
    $('planning-export').disabled=false;
    const balance26=rev.total-c.total,without26=rev.withoutBcra-c.total;
    const real=(s.expenses/c.total/(1+state.inflation/100)-1)*100;
    const revenueLoss=s.resources-D.finance.rows.find(r=>r.id==='VI').project;
    const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
    const max=Math.max(...c.months.map(r=>r.value));
    const reading=`Con estos supuestos, ${Math.abs(revenueLoss)<.001?'los ingresos coinciden con el proyecto':`${revenueLoss<0?'los ingresos quedan por debajo':'los ingresos quedan por encima'} del proyecto en ${money(Math.abs(revenueLoss))}`}. El gasto llega a ${money(s.expenses)} y el resultado ${s.balance<0?'es un déficit':'es un superávit'} de ${money(Math.abs(s.balance))}. ${s.gap>0.001?`Para cubrir todos los usos previstos faltan ${money(s.gap)} de financiamiento.`:s.gap< -.001?`Las fuentes simuladas exceden los usos en ${money(-s.gap)}.`:'Las fuentes previstas cubren los usos bajo este escenario.'}`;
    $('planning-results').innerHTML=`<h3>Cómo podría cerrar el gasto de 2026</h3><div class="decision-stats">${stat('Cierre proyectado',money(c.total),'Proyección mecánica; no es un dato observado.')}${stat('Cierre estimado por ONP',money(B.total.closing),'Referencia del proyecto 2027.')}${stat('Diferencia con el vigente',money(c.vsCredit),c.vsCredit>0?'Exigiría ampliar crédito o moderar el gasto.':'Margen respecto de la autorización actual.',c.vsCredit>0)}</div><div class="closing-chart" role="img" aria-label="Gasto mensual 2026: enero a agosto observado; septiembre a diciembre proyectado">${c.months.map(r=>`<div><span class="closing-bar ${r.observed?'':'projected'}" style="height:${Math.max(1,r.value/max*120)}px" title="${months[r.month-1]}: ${money(r.value)} · ${r.observed?'observado':'proyectado'}"></span><small>${months[r.month-1]}</small></div>`).join('')}</div><p class="note">Barras lisas: observado hasta agosto. Tramadas: proyección septiembre–diciembre. Septiembre parcial no se anualiza.</p>
      <h3 id="revenue-closing">Ingresos y resultado presupuestario de 2026</h3><p class="decision-reading">Los ingresos proyectados llegan a ${money(rev.total)}. Frente al gasto de ${money(c.total)}, el resultado sería ${balance26<0?'un déficit':'un superávit'} de ${money(Math.abs(balance26))}. Ese resultado incluye ${money(rev.bcraObserved)} de utilidades del BCRA ya registradas${rev.bcraFuture?` y ${money(rev.bcraFuture)} adicionales supuestos`:''}.</p><div class="decision-stats">${stat('Ingresos proyectados',money(rev.total),'Cobrado hasta agosto más proyección sep–dic.')}${stat('Resultado con utilidades BCRA',money(balance26),'Ingresos percibidos menos gasto devengado.',balance26<0)}${stat('Resultado sin utilidades BCRA',money(without26),'Se separa ese ingreso para ver cuánto depende de él.',without26<0)}</div><p class="note">Administración Nacional. Este resultado presupuestario no es el saldo de caja del Sector Público Nacional ni dinero libre para gastar.</p>${table(['Ingresos / pesos corrientes','Observado ene–ago','Proyección anual'],[...rev.groups.map(r=>[esc(r.name),money(r.observed),money(r.total)]),['Utilidades BCRA',money(rev.bcraObserved),money(rev.bcraObserved+rev.bcraFuture)]])}
      <h3>Resultado y financiamiento de 2027</h3><p class="decision-reading">${reading}</p><div class="decision-stats">${stat('Resultado financiero',money(s.balance),'Ingresos menos gasto, incluidos intereses.',s.balance<0)}${stat('Financiamiento requerido',money(s.need),'Incluye capital, otros pasivos e inversión financiera.')}${stat('Financiamiento faltante',money(Math.max(0,s.gap)),'Después de las fuentes simuladas.',s.gap>0)}</div>
      ${table(['Concepto / pesos corrientes','Escenario 2027'],[['Ingresos',money(s.resources)],['Prestaciones de seguridad social',money(s.pensions)],['Resto del gasto primario',money(s.otherPrimary)],['Intereses y otras rentas',money(s.interest)],['Gasto total',money(s.expenses)],['Amortizaciones y otros usos financieros',money(s.applications)],['Reducción de activos financieros',money(s.otherSources)],['Endeudamiento y otros pasivos disponibles',money(s.available)]])}<p>El gasto 2027 ${real<0?'baja':'sube'} <strong>${num(Math.abs(real))}% real frente al cierre 2026 proyectado</strong>. Esta comparación cambia con los supuestos y no reemplaza las comparaciones oficiales.</p>
      <h3>Qué explica la proyección de cierre</h3>${table(['Función','Observado ene–ago','Proyección anual'],[...c.groups].sort((a,b)=>b.total-a.total).slice(0,8).map(r=>[esc(r.name),money(r.observed),money(r.total)]))}`;
    last={version:2,created_at:new Date().toISOString(),scope:'Administración Nacional; ejercicio condicional, no pronóstico oficial',assumptions:{...state},closing2026:c,revenue2026:rev,balance2026:{includingBcra:balance26,excludingBcra:without26},scenario2027:s,inputs:{budget:window.nationalBudgetContext.hash,decisions:window.nationalDecisionHash,monthly:window.nationalManagementContext.datasets.gasto_mensual_funcion.files.json.sha256,revenue:R.inputs},url:'https://tablero.federicopellegrini.com.ar/nacion/#escenarios',method:'2026 ingresos: patrón real 2025 por grupo, escalado por cambio real enero-agosto; utilidades BCRA separadas por código y nuevas utilidades solo por supuesto explícito. 2026 gasto: patrón mensual real 2025 de cada función escalado por el cambio real enero-agosto 2026/2025, más inflación futura y ritmo elegido. 2027: impuestos y aportes responden a PIB e inflación; prestaciones y resto primario al traslado elegido; intereses al cambio explícito. Otros ingresos, capital y aplicaciones financieras se mantienen nominales. No es un modelo de contratos o rezagos.'};
  }
  function draw(){
    const fields=[['monthlyInflation','Inflación mensual sep–dic 2026 (%)',0,25,.01],['pace','Cambio del gasto real restante (%)',-50,50,1],['revenuePace','Cambio real de los ingresos restantes (%)',-50,50,1],['bcraFuture','Nuevas utilidades BCRA sep–dic (billones de $)',0,100,.1],['inflation','Inflación promedio 2027 / 2026 (%)',0,300,.01],['growth','Crecimiento real del PIB 2027 (%)',-20,20,.1],['elasticity','Respuesta de impuestos y aportes al PIB',0,3,.1],['pensionPass','Traslado de inflación a prestaciones (%)',0,100,1],['otherPass','Traslado al resto del gasto primario (%)',0,100,1],['interestChange','Cambio del gasto en intereses (%)',-50,100,1],['financing','Financiamiento disponible / previsto (%)',0,150,1]];
    $('escenarios').innerHTML=`<p class="eyebrow">Economía / Escenario integrado</p><h2 tabindex="-1">Del cierre de 2026 al financiamiento de 2027</h2><p>Probá cómo cambian el gasto, los ingresos y el dinero que falta financiar. Los supuestos de esta simulación se editan acá; las cifras oficiales del tablero se conservan.</p><div class="scenario-fields">${fields.map(([k,label,min,max,step])=>`<label for="plan-${k}">${label}<input id="plan-${k}" type="number" min="${min}" max="${max}" step="${step}" value="${Number(state[k].toFixed(6))}"></label>`).join('')}</div><p class="note">La respuesta 1 supone que 1% más de actividad aumenta 1% la recaudación real de impuestos y aportes. El traslado a prestaciones es un supuesto de sensibilidad; no reproduce las fórmulas legales ni sus rezagos.</p><div class="decision-links"><button class="button button-quiet" id="planning-reset">Restablecer supuestos</button><button class="button" id="planning-export">Descargar escenario y datos</button></div><div id="planning-results" aria-live="polite"></div><h3>Cómo se calcula</h3><p class="note">El cierre del gasto conserva enero–agosto y proyecta cada función con el patrón mensual de 2025, ajustado por su variación real en los primeros ocho meses. La inflación futura se aplica solo a los meses proyectados. Los ingresos siguen el patrón de 2025 por cuatro grupos, escalado por su cambio real enero–agosto. Las utilidades del BCRA se separan en ambos años: no se repiten automáticamente. Cero en nuevas utilidades es un supuesto editable, no un dato observado.</p><p class="note">La proyección no incorpora cambios tributarios o ingresos extraordinarios futuros sin un supuesto explícito. En 2027 se mantiene como base el proyecto oficial; impuestos y aportes responden juntos a actividad e inflación. Otros ingresos, amortizaciones y aplicaciones financieras se mantienen en el valor del proyecto; los intereses cambian con su propio supuesto. Las transferencias financieras internas se compensan y no se suman dos veces. Inflación: promedio anual, no diciembre contra diciembre.</p><div class="decision-links"><a href="data/gestion/gasto_mensual_funcion.csv">Ejecución mensual por función ↓</a><a href="data/revenue-planning.json">Ingresos y originales ↓</a><a href="#financiamiento">Cuadro oficial de financiamiento →</a><a href="#macro">Supuestos del proyecto →</a></div>`;
    for(const [k] of fields)$('plan-'+k).addEventListener('input',e=>{state[k]=e.target.value===''?null:Number(e.target.value);update();});
    $('planning-reset').addEventListener('click',()=>{state={...defaults};draw();});
    $('planning-export').addEventListener('click',()=>save('escenario-nacional.json',JSON.stringify(last,null,2)));
    update();
  }
  async function init(){
    B=window.nationalBudgetContext?.data;D=window.nationalDecisionContext;const G=window.nationalManagementContext;
    if(!B||!D||!G||loading||rows)return;
    if(!window.NationalDecisionMath.inputMatches(D,window.nationalBudgetContext.hash))return;
    loading=true;
    try{
      const ref=G.datasets.gasto_mensual_funcion.files.json,r=await fetch(ref.path,{cache:'no-cache'});if(!r.ok)throw Error('No se pudo leer la serie mensual.');const text=await r.text();
      const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text.replace(/\r\n/g,'\n')))),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==ref.sha256)throw Error('La serie se está actualizando. Recargá el tablero.');
      const rr=await fetch('data/revenue-planning.json?v=20260918-ingresos',{cache:'no-cache'});if(!rr.ok)throw Error('No se pudo leer la base de ingresos.');R=await rr.json();
      if(R.inputs['nacion/data/gestion/recursos_mensuales_tipo.json']!==G.datasets.recursos_mensuales_tipo.files.json.sha256||R.inputs['nacion/data/gestion/ipc_observado.json']!==G.datasets.ipc_observado.files.json.sha256)throw Error('La base de ingresos se está actualizando. Recargá el tablero.');
      rows=JSON.parse(text);
      defaults={monthlyInflation:(B.deflator.monthly_index['2026-09']/B.deflator.monthly_index['2026-08']-1)*100,pace:0,revenuePace:0,bcraFuture:0,inflation:(B.deflator.annual_average_index['2027']/B.deflator.annual_average_index['2026']-1)*100,growth:B.macro.find(r=>r.name==='Crecimiento del PIB').values[2],elasticity:1,pensionPass:100,otherPass:0,interestChange:0,financing:100};state={...defaults};draw();
    }catch(e){$('escenarios').innerHTML=`<p role="alert">${esc(e.message)}</p>`;}finally{loading=false;}
  }
  window.addEventListener('national:decisions-ready',init);window.addEventListener('national:management-ready',init);init();
})();
