/* Portfolio identities use real jurisdiction codes, not sequential PDF row IDs. */
(()=>{
  'use strict';
  const M=window.BudgetMath,N=window.NationalDecisionMath,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,d=1)=>M.finite(v)?new Intl.NumberFormat('es-AR',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v):'Sin dato';
  const money=v=>!M.finite(v)?'Sin asignación':`${v<0?'−':''}$${num(Math.abs(v)/(Math.abs(v)>=1e6?1e6:1000))} ${Math.abs(v)>=1e6?'billones':'mil millones'}`;
  const pct=v=>M.finite(v)?`${v>0?'+':''}${num(v)}%`:'Sin comparación';
  const sign=v=>M.finite(v)&&v<0?'negative':M.finite(v)&&v>0?'positive':'';
  const table=(heads,rows)=>`<div class="decision-table-wrap"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>i?`<td data-label="${esc(heads[i])}">${v}</td>`:`<th scope="row">${v}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  let chosen=Number(new URLSearchParams(location.search).get('cartera')||50),price=new URLSearchParams(location.search).get('precios')==='real'?'real':'nominal';
  function render(){
    const D=window.nationalDecisionContext,B=window.nationalBudgetContext?.data;
    if(!D||!B||!N.inputMatches(D,window.nationalBudgetContext.hash))return;
    const p=D.portfolios.find(p=>p.id===chosen)||D.portfolios.find(p=>p.id===50);chosen=p.id;
    const j=p.project,e=p.execution,programs=p.program_ids.map(id=>B.programs.find(r=>r.id===id)),works=p.work_ids.map(id=>B.works.find(r=>r.id===id));
    const val=(n,y=2027)=>M.price(n,y,price,B.deflator.annual_factors);
    const comps=M.comparisonRows(j,B.deflator.annual_factors),real=comps[1].real;
    const linked=D.policies.filter(r=>programs.some(a=>a.id===r.program.id));
    const reading=j.project===null?'Interior no tiene una jurisdicción con el mismo nombre en el proyecto 2027. Sus funciones aparecen en otras áreas. La ausencia de esta fila no representa un recorte a cero.':`El proyecto asigna <strong>${money(val(j.project))}</strong>, el ${num(M.ratio(j.project,B.total.project))}% del gasto nacional. ${programs.length?`La partida de mayor monto es <strong>${esc(programs[0].name)}</strong>, con ${num(M.ratio(programs[0].project,j.project))}% del presupuesto de esta cartera.`:''}`;
    $('carteras').innerHTML=`<p class="eyebrow">Gasto / Por ministerio</p><div class="portfolio-toolbar"><label for="portfolio-select">Ministerio o poder<select id="portfolio-select">${D.portfolios.map(r=>`<option value="${r.id}" ${r.id===p.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><button class="button" data-export-focus="cartera">Exportar informe</button><button class="button button-quiet" id="copy-portfolio">Copiar enlace</button></div><h2 tabindex="-1">${esc(p.name)}</h2><p class="decision-reading">${reading}</p><div class="decision-stats"><article><h3>Proyecto 2027</h3><strong class="decision-number">${money(val(j.project))}</strong><p>${price==='real'?'Pesos de agosto de 2026 · escenario':'Pesos corrientes'}.</p></article><article><h3>Cambio real frente al vigente</h3><strong class="decision-number ${sign(real)}">${pct(real)}</strong><p>Presupuesto según la estructura de cada año.</p></article><article><h3>Ejecutado en 2026</h3><strong class="decision-number">${num(M.ratio(e.credito_devengado,e.credito_vigente))}%</strong><p>Gasto reconocido sobre vigente al 15/09.</p></article></div>
      <h3>Tres puntos de comparación</h3>${table(['Base de 2026','Cambio en pesos','Cambio real'],comps.map(c=>[({law:'Inicial',current:'Vigente al 15/09',closing:'Cierre estimado'})[c.base],`<span class="${sign(c.nominal)}">${pct(c.nominal)}</span>`,`<strong class="${sign(c.real)}">${pct(c.real)}</strong>`]))}<p class="note">${esc(p.scope_note)} Real significa después de descontar inflación.</p>
      <h3>Del presupuesto al pago</h3><p class="note">Al 15/09/2026 · pesos corrientes.</p><div class="policy-stages">${[['Inicial','credito_presupuestado'],['Vigente','credito_vigente'],['Comprometido','credito_comprometido'],['Gasto reconocido','credito_devengado'],['Pagado','credito_pagado']].map(([label,key])=>`<div><span>${label}</span><strong>${money(e[key])}</strong></div>`).join('')}</div><p>La diferencia entre gasto reconocido y pagado es <strong>${money(e.credito_devengado-e.credito_pagado)}</strong>. El registro no identifica qué parte está vencida.</p>
      <h3>Las partidas que más pesan</h3>${programs.length?table(['Programa / organismo','Proyecto 2027','Del total','Cambio real / vigente'],programs.slice(0,8).map(r=>[`${esc(r.name)}<small class="portfolio-entity">${esc(r.entity)}</small>`,money(val(r.project)),num(M.ratio(r.project,j.project))+'%',`<span class="${sign(M.comparisonRows(r,B.deflator.annual_factors)[1].real)}">${pct(M.comparisonRows(r,B.deflator.annual_factors)[1].real)}</span>`])):'<p>La estructura 2027 no conserva esta jurisdicción.</p>'}<p class="note">${programs.length?`Selección de ${Math.min(8,programs.length)} de ${programs.length} partidas, ordenadas por monto. Los programas sin base verificada conservan su importe y no muestran variación.`:''}</p>
      ${linked.length?`<nav class="decision-links" aria-label="Políticas de esta cartera">${linked.map(r=>`<a href="#politica-${r.slug}">${esc(r.title)} →</a>`).join('')}</nav>`:''}
      <h3>Obras y prestaciones</h3><p>${j.project===null?'Las obras de 2027 deben buscarse en las jurisdicciones que reciben las funciones.':works.length?`La planilla de inversión incluye <strong>${works.length} partidas por ${money(val(p.works_total))}</strong>. Integran el presupuesto de la cartera; no se agregan otra vez al total.`:'La planilla 12 no identifica proyectos de inversión para esta cartera.'}</p>${works.length?table(['Mayores proyectos','Ubicación','Proyecto 2027'],works.slice(0,3).map(w=>[esc(w.name),esc(w.province),money(val(w.project))])):''}<p>${p.physical.count?`Hay ejecución informada en <strong>${p.physical.reported} de ${p.physical.count} mediciones físicas</strong> de enero–junio de 2026. Sus unidades y métodos son diferentes; no se suman para obtener una cantidad total de servicios.`:'No hay mediciones físicas de esta jurisdicción en el archivo del segundo trimestre.'}</p><div class="decision-links"><a href="#metas">Explorar las prestaciones →</a><a href="#obras">Ver proyectos →</a><a href="?buscar=${encodeURIComponent(p.name)}#programas">Buscar todos sus programas →</a><a href="data/decisions.json" download>Datos de las carteras ↓</a></div>`;
    $('portfolio-select').addEventListener('change',e=>{chosen=Number(e.target.value);const u=new URL(location.href);u.searchParams.set('cartera',chosen);history.replaceState(null,'',u);render();$('portfolio-select').focus({preventScroll:true});});
    $('copy-portfolio').addEventListener('click',async e=>{const u=new URL(location.href);u.search='';u.searchParams.set('cartera',chosen);u.searchParams.set('precios',price);u.hash='carteras';try{await navigator.clipboard.writeText(u.href);e.target.textContent='Enlace copiado';}catch(_){e.target.textContent='Copiá la dirección del navegador';}});
  }
  window.addEventListener('national:decisions-ready',render);
  window.addEventListener('national:state',e=>{price=e.detail.price;render();});
  window.addEventListener('popstate',()=>{chosen=Number(new URLSearchParams(location.search).get('cartera')||50);render();});
  render();
})();
