(function(){
  'use strict';
  const M=window.NationalPriorities,root=document.getElementById('prioridades');
  if(!root||!M)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=(v,d=1)=>M.finite(v)?v.toLocaleString('es-AR',{maximumFractionDigits:d,minimumFractionDigits:d}):'Sin dato';
  const pct=v=>M.finite(v)?`${v>=.05?'+':''}${n(Math.abs(v)<.05?0:v)}%`:'Sin base comparable';
  const money=v=>!M.finite(v)?'Sin dato':Math.abs(v)>=1e6?`$${n(v/1e6,2)} billones`:`$${n(v,0)} millones`;
  const pesos=v=>`$${n(v,0)}`;
  const month=p=>new Date(`${p}-15T12:00:00`).toLocaleDateString('es-AR',{month:'long',year:'numeric'});
  const tone=v=>!M.finite(v)?'':v<0?'priority-down':v>0?'priority-up':'';
  const benefitTone=v=>v<=-.05?'priority-down':v>=.05?'priority-positive':'';
  const params=new URLSearchParams(location.search);
  const state={mode:['execution','amendments','project'].includes(params.get('lectura'))?params.get('lectura'):'execution',base:['law','current','closing'].includes(params.get('referencia'))?params.get('referencia'):'closing',sort:'cuts',all:false,benefitBase:'2025-08',metric:'minimum_bonus'};
  const baseNames={law:'Inicial 2026',current:'Vigente 2026 · 15/09',closing:'Cierre estimado 2026'};
  const benefitNames={minimum:'Jubilación mínima sin bono',minimum_bonus:'Jubilación mínima con bono',bonus:'Bono previsional',auh:'AUH por hijo'};
  let B,G,H,loaded=false;
  const questions=[
    ['3-15','Seguridad social','El total incluye jubilaciones, pensiones y asignaciones. Para saber cómo vive quien las cobra, mirá también el ingreso por persona, más abajo.','politica-jubilaciones','Ver jubilaciones y prestaciones'],
    ['3-13','Salud','El gasto es una parte de la respuesta. Contrastalo con vacunas entregadas, tratamientos y prestaciones: una partida mayor puede no llegar todavía a los pacientes.','politica-inmunizaciones','Ver vacunas y metas'],
    ['3-16','Educación y cultura','Esta función es más amplia que las universidades. La ficha universitaria permite mirar el presupuesto específico y sus resultados.','politica-educacion-superior','Ver universidades'],
    ['3-17','Ciencia y tecnología','Mirá si el financiamiento sostiene proyectos y capacidades. Una caída real significa menos poder de compra, aunque los pesos aumenten.','metas','Ver prestaciones y metas'],
    ['2-12','Inteligencia','La función reúne el gasto clasificado como inteligencia. Es más amplia que el programa de la SIDE: sus importes no se suman entre sí.','programas','Explorar los programas'],
    ['3-14','Promoción y asistencia social','Compará el gasto con el alcance de la asistencia. Más presupuesto no demuestra por sí solo que llegue a más personas.','politica-alimentacion','Ver asistencia alimentaria'],
    ['3-19','Vivienda y urbanismo','El presupuesto habilita recursos; las obras y las viviendas terminadas muestran qué se concretó.','obras-ejecucion','Ver avance de obras'],
    ['4-23','Transporte','Incluye actividades distintas, como infraestructura y subsidios. Abrí los programas para identificar qué explica el cambio.','programas','Ver programas']
  ];
  function context(){
    if(state.mode==='amendments')return {title:'Qué se reforzó durante 2026',period:'Inicial 2026 → vigente al 15/09/2026',unit:'Pesos corrientes · autorizaciones de gasto',before:'Inicial',after:'Vigente',change:'Cambio nominal',explain:'Muestra cómo cambió la autorización para gastar durante el año. El aumento nominal no mide poder de compra ni gasto realizado.'};
    if(state.mode==='project')return {title:'Qué prioridades propone 2027',period:`Proyecto 2027 contra ${baseNames[state.base].toLowerCase()}`,unit:'Pesos de agosto de 2026 · escenario de inflación',before:baseNames[state.base],after:'Proyecto 2027',change:'Cambio real proyectado',explain:'Compara el poder de compra propuesto. El resultado usa el escenario del tablero: inflación de diciembre de 29% en 2026 y 18% en 2027, convertida a promedios anuales. El proyecto todavía no es gasto realizado.'};
    return {title:'Dónde creció y dónde cayó el gasto real',period:'Enero–agosto 2026 contra enero–agosto 2025',unit:'Pesos de agosto de 2026 · IPC observado, mes a mes',before:'Ene–ago 2025',after:'Ene–ago 2026',change:'Cambio real',explain:'Gasto devengado: obligaciones de pago reconocidas. Se comparan los mismos ocho meses, descontando la inflación de cada mes. No incluye septiembre parcial.'};
  }
  function saveState(){const u=new URL(location.href);u.searchParams.set('lectura',state.mode);u.searchParams.set('referencia',state.base);history.replaceState(null,'',u);}
  function render(){
    if(!B||!G||!H)return;
    loaded=true;
    const c=context(),model=M.comparisons(B,G,state.mode,state.base),ordered=M.ranked(model.rows,state.sort),cut=M.ranked(model.rows).find(r=>r.delta<0),rise=M.ranked(model.rows,'increases').find(r=>r.delta>0);
    const simple=r=>r?`${esc(r.name)}: ${pct(r.change)}`:'No hay cambios en este sentido';
    root.innerHTML=`<p class="eyebrow">Nación / Prioridades</p><h1 tabindex="-1">Prioridades y efectos del presupuesto</h1><p class="priority-intro">Qué se refuerza, qué pierde poder de compra y cómo llega a las personas.</p>
      <nav class="priority-jumps" aria-label="En esta lectura"><a href="#priority-comparison">Gasto por área ↓</a><a href="#priority-income">Jubilaciones y AUH ↓</a><a href="#priority-next">Obras y provincias ↓</a></nav>
      <div class="priority-modes" role="group" aria-label="Qué comparar"><button data-priority-mode="execution" aria-pressed="${state.mode==='execution'}">Gasto real 2026</button><button data-priority-mode="amendments" aria-pressed="${state.mode==='amendments'}">Cambios durante 2026</button><button data-priority-mode="project" aria-pressed="${state.mode==='project'}">Propuesta 2027</button></div>
      <div id="priority-comparison"><h2>${c.title}</h2><p class="priority-period">${c.period}</p><p class="note">${c.unit}</p>
      ${state.mode==='project'?`<label class="priority-select">Comparar el proyecto con<select id="priority-base">${Object.entries(baseNames).map(([id,name])=>`<option value="${id}" ${state.base===id?'selected':''}>${name}</option>`).join('')}</select></label><div class="priority-base-strip">${Object.entries(baseNames).map(([id,name])=>`<span>${name}<strong>${pct(M.comparisons(B,G,'project',id).total.change)} real</strong></span>`).join('')}</div>`:''}
      <div class="priority-summary" aria-live="polite"><article><span>Gasto total · ${c.change.toLowerCase()}</span><strong class="${tone(model.total.change)}">${pct(model.total.change)}</strong><p>${money(model.total.after)}</p></article><article><span>Mayor baja en pesos ${state.mode==='amendments'?'corrientes':'constantes'}</span><strong class="priority-down priority-name">${cut?esc(cut.name):'Sin bajas'}</strong><p>${cut?`${money(cut.delta)} · ${pct(cut.change)}`:'Todas las funciones mantienen o aumentan su monto.'}</p></article><article><span>Mayor suba en pesos ${state.mode==='amendments'?'corrientes':'constantes'}</span><strong class="priority-up priority-name">${rise?esc(rise.name):'Sin subas'}</strong><p>${rise?`${money(rise.delta)} · ${pct(rise.change)}`:'Todas las funciones mantienen o reducen su monto.'}</p></article></div>
      <p class="priority-explanation">${c.explain}</p>
      <div class="priority-focus">${questions.map(([id,title,explain,link,label])=>{const r=model.rows.find(r=>r.id===id);return `<article><h3>${title}</h3><strong class="priority-value ${tone(r?.change)}">${pct(r?.change)}</strong><p class="note">${c.change} · ${money(r?.after)}</p><p>${explain}</p><a href="#${link}" ${id==='2-12'?'data-intelligence-search':''}>${label} →</a></article>`;}).join('')}</div>
      ${intelligence(c)}
      <div class="priority-ranking-head"><div><h2>Las 29 funciones, con el mismo criterio</h2><p>Rojo: baja. Azul: suba. El porcentaje mide intensidad; la diferencia en pesos muestra cuánto pesa el cambio.</p></div><label class="priority-select">Ordenar<select id="priority-sort"><option value="cuts">Mayores bajas en pesos</option><option value="increases">Mayores subas en pesos</option><option value="percent">Mayores bajas porcentuales</option></select></label></div>
      <div class="priority-ranking" aria-label="Comparación de todas las funciones">${ordered.slice(0,state.all?29:6).map(r=>`<article><div class="priority-row-head"><h3>${esc(r.name)}</h3><strong class="${tone(r.change)}">${pct(r.change)}</strong></div><div class="priority-meter" aria-hidden="true"><i class="${tone(r.delta)}" style="width:${M.finite(r.delta)?Math.min(100,Math.abs(r.delta)/Math.max(1,...model.rows.map(x=>Math.abs(x.delta??0)))*100):0}%"></i></div><dl><div><dt>${c.before}</dt><dd>${money(r.before)}</dd></div><div><dt>${c.after}</dt><dd>${money(r.after)}</dd></div><div><dt>Diferencia</dt><dd class="${tone(r.delta)}">${money(r.delta)}</dd></div><div><dt>Peso en el gasto total</dt><dd>${n(r.shareBefore,2)}% → ${n(r.shareAfter,2)}% <small>(${M.finite(r.shareChange)&&r.shareChange>0?'+':''}${n(r.shareChange,2)} pp)</small></dd></div></dl></article>`).join('')}</div>
      <div class="priority-actions"><button id="priority-show-all">${state.all?'Mostrar seis filas':'Ver las 29 funciones'}</button><button id="priority-csv">Descargar comparación CSV ↓</button><button id="priority-copy">Copiar lectura</button><span id="priority-copy-status" role="status"></span></div></div>
      <section id="priority-income" class="priority-income"><p class="eyebrow">Del gasto al ingreso</p><h2>Cuánto compran las jubilaciones y la AUH</h2><p>Acá miramos el monto por prestación, no el presupuesto total. Real significa descontar la inflación: si baja, alcanza para comprar menos.</p><div class="priority-income-controls"><label class="priority-select">Comparar ${month(H.meta.latest_real)} con<select id="benefit-base">${H.rows.filter(r=>r.ipc&&r.period<H.meta.latest_real).map(r=>`<option value="${r.period}" ${r.period===state.benefitBase?'selected':''}>${month(r.period)}</option>`).join('')}</select></label><label class="priority-select">Ver la evolución de<select id="benefit-metric">${Object.entries(benefitNames).map(([id,name])=>`<option value="${id}" ${id===state.metric?'selected':''}>${name}</option>`).join('')}</select></label></div><div id="benefit-content"></div></section>
      <section id="priority-next"><h2>Del presupuesto al resultado</h2><div class="priority-more"><a href="#obras-ejecucion"><strong>Obras: gasto y avance físico</strong><span>Cuánto se ejecutó y qué se construyó. Revisá las obras con gastos y poco avance.</span></a><a href="#provincias-nacion"><strong>Qué llega a las provincias</strong><span>Recursos nacionales, transferencias y gasto localizado, identificados por separado.</span></a><a href="#metas"><strong>Prestaciones y cobertura</strong><span>Compará recursos con vacunas, tratamientos, becas y otras metas.</span></a><a href="#normas"><strong>Cómo se modificó el presupuesto</strong><span>Normas y anexos para rastrear los cambios. Una suba y una baja no prueban por sí solas un traslado entre ambas.</span></a></div></section>
      <div class="priority-sources"><p>Fuentes: ONP y Presupuesto Abierto para gasto; Seguridad Social (IMSS) para prestaciones; INDEC para inflación. Administración Nacional · gastos corrientes y de capital.</p><a href="#metodo">Fuentes y método del presupuesto →</a> · <a href="data/benefit-sources/sources.json" download>Documentos mensuales de prestaciones ↓</a> · <a href="data/benefits.json" download>Serie de prestaciones ↓</a></div>`;
    root.querySelector('#priority-sort').value=state.sort;
    root.querySelectorAll('[data-priority-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.priorityMode;saveState();render();root.querySelector(`[data-priority-mode="${state.mode}"]`).focus({preventScroll:true});});
    root.querySelector('#priority-base')?.addEventListener('change',e=>{state.base=e.target.value;saveState();render();root.querySelector('#priority-base')?.focus({preventScroll:true});});
    root.querySelector('#priority-sort').onchange=e=>{state.sort=e.target.value;render();root.querySelector('#priority-sort').focus({preventScroll:true});};
    root.querySelector('#priority-show-all').onclick=()=>{state.all=!state.all;const y=window.scrollY;render();window.scrollTo(0,y);};
    root.querySelector('#priority-csv').onclick=()=>download(model,c);
    root.querySelector('#priority-copy').onclick=async()=>{const text=`${c.title}. ${c.period}. ${c.unit}. Gasto total: ${pct(model.total.change)} (${money(model.total.after)}). Mayor baja en pesos: ${cut?`${cut.name}, ${money(cut.delta)}, ${pct(cut.change)}`:'no hay'}. Mayor suba en pesos: ${rise?`${rise.name}, ${money(rise.delta)}, ${pct(rise.change)}`:'no hay'}. ${c.explain} Fuente: ONP / Presupuesto Abierto. ${location.href}`;try{await navigator.clipboard.writeText(text);root.querySelector('#priority-copy-status').textContent='Lectura copiada con período y fuente.';}catch(_){root.querySelector('#priority-copy-status').textContent='No se pudo copiar. Podés descargar el CSV.';}};
    root.querySelectorAll('[data-intelligence-search]').forEach(a=>a.onclick=()=>{const input=document.getElementById('program-search');input.value='inteligencia';input.dispatchEvent(new Event('input'));});
    root.querySelector('#benefit-base').onchange=e=>{state.benefitBase=e.target.value;renderBenefits();};
    root.querySelector('#benefit-metric').onchange=e=>{state.metric=e.target.value;renderBenefits();};
    // In-page jumps must not enter the app hash router (these are anchors inside this view).
    root.querySelectorAll('.priority-jumps a').forEach(a=>a.onclick=e=>{e.preventDefault();root.querySelector(a.getAttribute('href')).scrollIntoView({behavior:'instant',block:'start'});});
    renderBenefits();
  }
  function intelligence(c){
    if(state.mode==='execution')return '';
    const p=B.programs.find(r=>r.id==='p44');
    if(!p)return '';
    const x=state.mode==='amendments'?M.change(p.current,p.law):M.change(p.project*B.deflator.annual_factors['2027'],p[state.base]*B.deflator.annual_factors['2026']);
    if(state.mode==='project'&&!M.finite(p[state.base]))return '<p class="priority-explanation">La comparación de inteligencia usa toda la función. El cierre estimado por programa de la SIDE no está disponible para una comparación equivalente.</p>';
    return `<p class="priority-explanation"><strong>Dentro de inteligencia, el programa Información e Inteligencia de la SIDE:</strong> ${pct(x)} ${state.mode==='amendments'?'nominal frente al inicial':'real frente a la base elegida'}. ${c.period}. Se muestra aparte para no confundir un programa con toda la función.</p>`;
  }
  function renderBenefits(){
    const end=H.meta.latest_real,latest=H.rows.find(r=>r.period===end),nominal=H.rows.at(-1),base=H.rows.find(r=>r.period===state.benefitBase);
    const changes=Object.fromEntries(Object.keys(benefitNames).map(k=>[k,M.benefitChange(H.rows,state.benefitBase,end,k)]));
    const effect=v=>Math.abs(v)<.05?'prácticamente mantuvo su poder de compra':`${v<0?'perdió':'ganó'} ${n(Math.abs(v))}% de poder de compra`;
    const reading=`Entre ${month(state.benefitBase)} y ${month(end)}, la mínima con bono ${effect(changes.minimum_bonus)}. La mínima sin bono ${effect(changes.minimum)}. El bono ${effect(changes.bonus)} y la AUH ${effect(changes.auh)}.${base.bonus===latest.bonus?' El bono quedó fijo en '+pesos(latest.bonus)+' mientras los precios subieron.':''}`;
    root.querySelector('#benefit-content').innerHTML=`<p class="priority-reading" aria-live="polite">${reading}</p><div class="benefit-cards">${Object.entries(benefitNames).map(([key,label])=>`<article><h3>${label}</h3><strong class="${benefitTone(changes[key])}">${pct(changes[key])} <small>real</small></strong><p>${pesos(base[key])} → ${pesos(latest[key])}</p><small>Importes nominales mensuales</small></article>`).join('')}</div>${chart()}<p class="note">Índice de poder de compra: ${month(state.benefitBase)} = 100. Arriba de 100 compra más; abajo, menos. Sin aguinaldo. AUH general al 100% del derecho mensual; no es necesariamente lo depositado en la cuenta.</p><p class="priority-latest"><strong>Último monto publicado · ${month(nominal.period)}:</strong> mínima con bono ${pesos(nominal.minimum_bonus)} · AUH ${pesos(nominal.auh)}. ${nominal.ipc?'':'El cálculo real llega hasta agosto, último IPC observado.'} <a href="${esc(nominal.source)}" target="_blank" rel="noopener">Documento oficial ↗</a></p><p class="note">Mínima con bono completo para quien cumple el tope. Importes de IMSS redondeados al peso; el total se calcula sumando haber y bono. ${state.benefitBase<'2024-03'?'La serie conserva la falta de enero y febrero de 2024; el gráfico deja ese tramo sin unir.':''}</p><button id="benefit-csv">Descargar serie mensual CSV ↓</button>`;
    root.querySelector('#benefit-csv').onclick=()=>csv('prestaciones-mensuales.csv',[['periodo','minima_pesos','bono_pesos','minima_con_bono_pesos','auh_derecho_100_pct_pesos','ipc_observado','fuente'],...H.rows.map(r=>[r.period,r.minimum,r.bonus,r.minimum_bonus,r.auh,r.ipc,r.source])]);
  }
  function chart(){
    const rows=M.benefitIndex(H.rows,state.benefitBase,state.metric).filter(r=>r.value!==null),w=Math.min(720,Math.max(250,window.innerWidth-76)),h=235,pad=40;
    const serial=p=>Number(p.slice(0,4))*12+Number(p.slice(5));
    const lo=Math.min(95,...rows.map(r=>r.value))-3,hi=Math.max(105,...rows.map(r=>r.value))+3;
    const x=p=>pad+(serial(p)-serial(rows[0].period))/Math.max(1,serial(rows.at(-1).period)-serial(rows[0].period))*(w-pad*2),y=v=>h-pad-(v-lo)/(hi-lo)*(h-pad*2);
    let path='';rows.forEach((r,i)=>{path+=`${i&&serial(r.period)-serial(rows[i-1].period)===1?'L':'M'}${x(r.period)},${y(r.value)} `;});
    const last=rows.at(-1);
    return `<figure class="benefit-chart"><figcaption>${benefitNames[state.metric]} · poder de compra</figcaption><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(benefitNames[state.metric])}: índice 100 en ${month(state.benefitBase)}, ${n(last.value)} en ${month(last.period)}"><line x1="${pad}" y1="${y(100)}" x2="${w-pad}" y2="${y(100)}" class="benefit-baseline"/><text x="8" y="${y(100)-6}">100</text><path d="${path}" class="benefit-line"/>${rows.map(r=>`<circle cx="${x(r.period)}" cy="${y(r.value)}" r="3"><title>${month(r.period)}: ${n(r.value)}</title></circle>`).join('')}<text x="${x(last.period)-4}" y="${y(last.value)-12}" text-anchor="end">${n(last.value)}</text><text x="${pad}" y="${h-10}">${rows[0].period}</text><text x="${w-pad}" y="${h-10}" text-anchor="end">${last.period}</text></svg></figure>`;
  }
  function csv(name,rows){const blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function download(model,c){csv(`prioridades-${state.mode}-${state.base}.csv`,[['funcion','periodo','unidad','base','comparado','variacion_pct','diferencia_millones','participacion_base_pct','participacion_comparado_pct','cambio_pp'],...M.ranked(model.rows,state.sort).map(r=>[r.name,c.period,c.unit,r.before,r.after,r.change,r.delta,r.shareBefore,r.shareAfter,r.shareChange])]);}
  function ready(){B=window.nationalBudgetContext?.data;G=window.nationalManagementContext;if(B&&G&&H&&!loaded)render();}
  window.addEventListener('national:budget-ready',ready);window.addEventListener('national:management-ready',ready);
  let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(loaded)renderBenefits();},150);});
  fetch('data/benefits.json?v=20260922').then(r=>{if(!r.ok)throw new Error('Benefits unavailable');return r.json();}).then(data=>{H=data;ready();}).catch(()=>{root.innerHTML='<h1>Prioridades y efectos del presupuesto</h1><p role="alert">No se pudieron cargar las prestaciones. Recargá la página para volver a intentar.</p>';});
  ready();
})();
